### PR TITLE
batch B_U_D events

### LINKED ISSUE #4752: Healthstones - Count not updating when refilling from soulwell.
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

When picking up (refilling) soulstones from 1 count or 2 counts (out of combat) - the COUNT trigger does not update to 3 stacks...until you enter combat.

### WeakAuras Version

5.8.7

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Lua Error

```Text
NA
```

### Reproduction Steps

Be on a warlock
Get healthstones (3 count)
Fly up in the air and fall - so that you can use 1 count
You are left with 2
Put down a soulwell
Click it - and watch you go back to 3 count on your action bar
But the weakaura monitoring count does not go to 3 until you enter combat

### Last Good Version

_No response_

### Screenshots

image

### Export String

```Text
!WA:2!1zvZVTXXvCrWyex6(HftLSSRHbTrJqtrRqItKJrlCD4srAkhAs1L0vo5c3z3Di3jA5oBMzOOyUfEP6speceGau1gv2po1te5pGwDONYHhiQb6XcFON6jHE39nZUK(JyBalo7BEF(BFVFVntL89Y7N3)WxFcZJh1K3x4rV8sZi9vbCrJyfJhjZjg2Othjv91zNsI8Wl2HZIuULkxVvz7zECEOpFquZbSyQZjZFSSFxAGL2RoJucw3UuH8kRlsp(pSudJPwmfT3JK9DP7tJun73Pd7GPTlvSzR2nBv0Uv8Y9L02DPrubZRzaFqJiNt0I02vN0J6SW4Deu0y7M7uUwnBJK41kLMkf2rW7kOszHF02OHVXizmnmCBFzUzpJVNiXFkgoGmuoAEeo7khAhH)kZz1pIPCJdjdPIj(uxmBBH1GOA5A7u5(1g3pkT2YToK7WlaRHMoM0xqmMFPrB3RhpKOOZ6ruEbuzsmHlaRI))I5MODF5dysL0joVPiJ8c77tlfqeDPsNXMSwNtR9k)VliqnmiaSmKh(oW3fUKRsROsGvCJOWHoW5DGVNZmbLe2CUPtQesLbEcsh1mDmw4thyLCW5GVDsOPhq8upbLHxBIg4kuIJf5yTckbXBph4YIQfTVhw9WvYfVmAdBFAReu4ECF6FDPtXgfQiIe(RWx)yZ0V509O04Iyy9u2eS9kymjI1tFk6g2sScuvoHsK0MkbnQRk4vHZzfXJOZ8rKuRvBDJJqsXglF5iTQ63cWMw9iSOkW7GgaBc3aEx4MWMUDyrmzWZlgF9jjkTdPbtWoiBAxDJ(hUkCUz4JUyT1vG1Q)HReNxrpq1wgqWoPhKmhKj(IgHM)0HlW0VTm9aS54f3z96xFdz85FkhuIhYf3ntMmzFuIuAyhZWKvX73Qr8RzeIdFCnI4TlZxfyveF80KqXoG6Be(PZsge)G0e6eZ9FuFPI1ziCMjcUcRTw6COEJ6LHZjWYsRZeJIEM0il(VXP1qK60kmbPqtsKSGvicaptHppoZmYgWf(7kiXJ2n9qs43NjzUHuN0k(POkIxE761lB32QrRwnUN923PAR4FW3acrWAbioBrE1K9j0RMwUp4zsd9TMjWg3VvTTRx()mRBiFqfb9J7tJ8gUZR8MBC9ntkD9fAIJ7eM(oiyKwK26zU9vkEuJ9PcC0EIwCntN3kt1NNx5J7o3udUDI(XTsBjZA0CrYz8CaZBViKYjRXWMEKqAwl9XaJGAm8YLnrZcbrQi4WlgF1VbKe3wX6rBhlOEm94tw49oToVqvCKwfiX0ME1xqVyC6bBTX(qjylOmubUZNcvZaBdNbUl8(GLPneNkQbpidCV7MT6T)7F2N9Lp(XpU6T)6Jo6VT0s4T1HgWVidStgOza8lbB4dGpeADcc4lEBgFLxwwN8uM4cVmf6X9BRNbDGDxj(nEzA5pejqzETvbifEaYOpm(h(Y0nK2L4nSDNqoxJO6C)9MwJpOqkj68Q(fdjIadC8Xdr4O6T)xFXxObHQ3(HF(NFCYHh(W)9cy5JYQHLyNNalqeWna1UROH0qONBaL1nqDlRqoX)V8iVqIuIZf(AAxV1DLSOUH0V68296hQyR(vN3bPWdXvxRchKZYOdm4vXZJ844gnI(IbFlZcW5cCgLYI7LU04zJHZ4fYCSn)GEuSBr7Ank9(MGGtx6O5knR(Dz9I5c1eHHq0qSE2PSOeqgLS6u8OhTSE)Q0zQptQ3hUnYfV2zV5WXlOZGZioizC4)MXfVTdRBU4V)8pnqZlTftsqYc)GPDe4kgKUNOizNO4E7NSPyTm)6GRX8JZ)un7f(Pf2Ikv2d0CG3YuWZ3XJRBS1TsNMWuur7uD(72SKD5Y1TjHXbKSxVpZF6U032F3Wq3T27TeSiD4Oi4Sy026t48EzMO3VWmF)ZDx3g3x7Txfi3pzPr7temDMF9I136A84RDRB5AUv(JVbKllC0eE08CYEFsyFAg0UZah5Il3qTGJZ)MjMj8ciryp5Lwho2zuSGJmz4UT8iD1gVZgpnJ66WV1eB4i43Lyl871r7YOKr4xjW75ICMhNgi4pKQdgjyIX7WFe(tZDs6LOREItG)8lY63AH1jj1MpFsLuWWxchN9jb6NpA(RzhH(dcqa8gWBNd(z5SWDXQC5L2BUXn34DZV))8b))d
```

### PR DESCRIPTION
**Pull request by emptyrivers**
fixes #4752

i did not test perf on this, FYI

### CODE REVIEW

File: WeakAuras/GenericTrigger.lua [hunk 1]
```diff
@@ -2298,6 +2305,7 @@ do
     cdReadyFrame:RegisterEvent("SPELL_UPDATE_COOLDOWN");
     cdReadyFrame:RegisterEvent("UNIT_SPELLCAST_SENT");
     cdReadyFrame:RegisterEvent("BAG_UPDATE_DELAYED");
+    cdReadyFrame:RegisterEvent("BAG_UPDATE_COOLDOWN");
```
Comment (InfusOnWoW) [inline WeakAuras/GenericTrigger.lua:2308]: The CD tracking of health stones and trinkets seems to work since they fire  SPELL_UPDATE_COOLDOWN. So unless you know of a item whose item cooldown tracking doesn't work, I wouldn't touch the cdReadyFrame thing.

File: WeakAuras/Prototypes.lua [hunk 2]
```diff
@@ -6638,6 +6638,7 @@ Private.event_prototypes = {
     type = "item",
     events = {
       ["events"] = {
+        "BAG_UPDATE_COOLDOWN",
```
Comment (InfusOnWoW) [inline WeakAuras/Prototypes.lua:6641]: But here I think we need that batched treatement. Though BAG_UPDATE_COOLDOWN fires a lot with no discernable reason. I think we should also only do that if we are tracking charges, as I think everything else is handled by BAG_UPDATE_DELAYED. At least in my testing that BAG_UPDATE_DELAYED fires for everything I could think of.

File: WeakAuras/GenericTrigger.lua [hunk 3]
```diff
@@ -3679,10 +3679,26 @@ function WeakAuras.RegisterItemCountWatch()
...
+        -- workaround to blizzard bug: refreshing healthstones from soulwell dont trigger BAG_UPDATE_DELAYED
+        -- so, we fake it by listening to B_U_C and checking on next frame
+        itemCountWatchFrame:SetScript("OnUpdate", batchUpdateCount)
+      elseif event == "BAG_UPDATE_DELAYED" then
+        -- if we *do* get a B_U_D, then cancel our fake one
+        -- item count prototype already subscribes to this event so no need to also send an internal event
+        itemCountWatchFrame:SetScript("OnUpdate", nil)
+      else
+        timer:ScheduleTimer(WeakAuras.ScanEvents, 0.2, "ITEM_COUNT_UPDATE");
+        timer:ScheduleTimer(WeakAuras.ScanEvents, 0.5, "ITEM_COUNT_UPDATE");
```
Comment (InfusOnWoW) [inline WeakAuras/GenericTrigger.lua:3700]: I've tracked this down to: 0e447bb088412ac661ddbf6b32ea2509ae87363a committed in 2011 with the commit message:
"    Fixed a bug where Item Count triggers were not updating correctly with items with charges."

I suspect that's about the classic spells that cost reagents?

Comment (InfusOnWoW) [reply WeakAuras/GenericTrigger.lua:3700]: Ah 2011 is cata, so maybe that's healtstone already?

Comment (emptyrivers) [reply WeakAuras/GenericTrigger.lua:3700]: ah, yes *using* a healthstone (but not using the last charge) does indeed produce an event cascade that doesn't include a B_U_D at the end. I wonder if mana gems work the same way, one moment please.

Comment (emptyrivers) [reply WeakAuras/GenericTrigger.lua:3700]: yeah, i get this cluster of events on using the first charge of a mana gem:
image

I'll remove the old double scan and see if it breaks anything

Comment (InfusOnWoW) [reply WeakAuras/GenericTrigger.lua:3700]: In my testing using a healthstone does include B_U_D, so I was about to suggest removing ScheduleTimer code here.

**Review by InfusOnWoW — APPROVED** [review]
