### PR TITLE
hide dynFrame if combat starts with living threads

### LINKED ISSUE #4967: WA Options stuck on loading
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

WA occasionally gets stuck on loading after using /wa. I'd say this didn't happen prior to 10.2.6

no idea if colorpicker plus can cause this

included a screenshot

### WeakAuras Version

5.12.5

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Lua Error
```Text
1x ...s/AceGUI-3.0-41/widgets/AceGUIWidget-DropDown-Items.lua:17: script ran too long
[string "@Masque/Libs/AceGUI-3.0-41/widgets/AceGUIWidget-DropDown-Items.lua"]:17: in function <...s/AceGUI-3.0/widgets/AceGUIWidget-DropDown-Items.lua:12>
[string "@Masque/Libs/AceGUI-3.0-41/widgets/AceGUIWidget-DropDown-Items.lua"]:17: in function <...s/AceGUI-3.0/widgets/AceGUIWidget-DropDown-Items.lua:12>
[string "@Masque/Libs/AceGUI-3.0-41/widgets/AceGUIWidget-DropDown-Items.lua"]:96: in function `SetPullout'
[string "@Masque/Libs/AceGUI-3.0-41/widgets/AceGUIWidget-DropDown.lua"]:177: in function `AddItem'
[string "@Masque/Libs/AceGUI-3.0-41/widgets/AceGUIWidget-DropDown.lua"]:570: in function <...ue/Libs/AceGUI-3.0/widgets/AceGUIWidget-DropDown.lua:560>
[string "@Masque/Libs/AceGUI-3.0-41/widgets/AceGUIWidget-DropDown.lua"]:610: in function `SetList'
[string "@Masque/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:1279: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1110>
[string "@Masque/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:1639: in function `FeedGroup'
[string "@Masque/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:1919: in function `Open'
[string "@WeakAurasOptions/OptionsFrames/OptionsFrame.lua"]:1001: in function `FillOptions'
[string "@WeakAurasOptions/OptionsFrames/OptionsFrame.lua"]:998: in function <...dOns/WeakAurasOptions/OptionsFrames/OptionsFrame.lua:996>
[string "=[C]"]: ?
[string "@Masque/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <Masque/Libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Masque/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Masque/Libs/AceGUI-3.0-41/widgets/AceGUIContainer-TabGroup.lua"]:342: in function `SelectTab'
[string "@Masque/Libs/AceGUI-3.0-41/widgets/AceGUIContainer-TabGroup.lua"]:200: in function <...Libs/AceGUI-3.0/widgets/AceGUIContainer-TabGroup.lua:197>

Locals:
parent = AceGUI30DropDownItem312 {
 0 = <userdata>
 sndButton = Button {
 }
 PixelSnapDisabled = true
 obj = <table> {
 }
}
i = 1
child = Button {
 0 = <userdata>
 sound = FontString {
 }
 PixelSnapDisabled = true
}
(*temporary) = <function> defined @Masque/Libs/AceGUI-3.0/widgets/AceGUIWidget-DropDown-Items.lua:12
(*temporary) = Button {
 0 = <userdata>
 sound = FontString {
 }
 PixelSnapDisabled = true
}
(*temporary) = "script ran too long"
select = <function> defined =[C]:-1
fixlevels = <function> defined @Masque/Libs/AceGUI-3.0/widgets/AceGUIWidget-DropDown-Items.lua:12
```
```Text
1x Masque/Libs/AceGUI-3.0-41/AceGUI-3.0.lua:66: script ran too long
[string "@Masque/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <Masque/Libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Masque/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Masque/Libs/AceGUI-3.0-41/widgets/AceGUIContainer-TabGroup.lua"]:342: in function `SelectTab'
[string "@Masque/Libs/AceGUI-3.0-41/widgets/AceGUIContainer-TabGroup.lua"]:200: in function <...Libs/AceGUI-3.0/widgets/AceGUIContainer-TabGroup.lua:197>

Locals:
func = <function> defined @WeakAurasOptions/OptionsFrames/OptionsFrame.lua:996
(*temporary) = false
(*temporary) = nil
(*temporary) = "script ran too long"
xpcall = <function> defined =[C]:-1
errorhandler = <function> defined @Masque/Libs/AceGUI-3.0/AceGUI-3.0.lua:60
```
```Text
1x WeakAuras/WeakAuras.lua:4339: script ran too long
[string "@WeakAuras/WeakAuras.lua"]:4339: in function <WeakAuras/WeakAuras.lua:4321>

Locals:
self = Frame {
 0 = <userdata>
}
elapsed = 0.023000
start = 383241952.209600
hasData = true
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 LayoutDisplayButtons2 = <no value>
}
(for control) = "LayoutDisplayButtons2"
name = "LayoutDisplayButtons2"
func = <no value>
ok = false
msg = "WeakAuras/Libs/LibSerialize/LibSerialize.lua:1230: script ran too long"
(*temporary) = false
(*temporary) = "WeakAuras/Libs/LibSerialize/LibSerialize.lua:1230: script ran too long"
(*temporary) = false
(*temporary) = nil
(*temporary) = nil
(*temporary) = "script ran too long"
debugprofilestop = <function> defined =[C]:-1
dynFrame = <table> {
 RemoveAction = <function> defined @WeakAuras/WeakAuras.lua:4309
 AddAction = <function> defined @WeakAuras/WeakAuras.lua:4296
 frame = Frame {
 }
 update = <table> {
 }
 size = 1
}
debugstack = <function> defined =[C]:-1
```

### Reproduction Steps

can't reproduce reliably

### Last Good Version

_No response_

### Export String

_No response_
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/14813110/WeakAuras.zip)

### PR DESCRIPTION
**Pull request by emptyrivers**
nothing that we put into dynFrame threads is meant for in-combat execution anyways, so to avoid random unexpectedly short timeouts, pause execution if combat starts, and resume after combat ends.

There's potential for WeakAuras to be 'broken' during that combat session (due to dynamic groups being Pause()'d), but we probably couldn't have unbroken it given that ResumeAllDynamicGroups is too costly to call during combat lockdown without risking a timeout.

Fixes #4967 (or at least, reduces its likelihood)

### CODE REVIEW

File: WeakAuras/WeakAuras.lua [hunk 1]
```diff
@@ -1668,8 +1668,8 @@ local function scanForLoadsImpl(toCheck, event, arg1, ...)
   local encounter_id = WeakAuras.CurrentEncounter and WeakAuras.CurrentEncounter.id or 0
 
   if (event == "ENCOUNTER_START") then
-    encounter_id = tonumber (arg1)
-    CreateEncounterTable (encounter_id)
+    encounter_id = tonumber(arg1)
```
Comment (emptyrivers) [inline WeakAuras/WeakAuras.lua:1671]: well I didn't mean to include this change, but oh well. I'm not taking it out.

**Comment by InfusOnWoW** [comment]
I did a few more tests with login while an encounter is in progress, and the order is PLAYER_LOGIN => PLAYER_REGEN_DISABLED, which is what I expected.
Since we run the login thread for up to 15s on PLAYER_LOGIN, and a test I did with wago.io/dfraid2 installed took only 1.7s, I don't think we'll realistcally exceed those 15s. And even if we do, pausing the login thread would be the right thing to do.

**Review by InfusOnWoW — APPROVED** [review]
