### PR TITLE
[WIP] Auto re-anchor unitframes & slightly different anchors for nameplates addons

### LINKED ISSUE #2051: Join a group after buff does not appear to automatically anchor to the unit frame
## Describe the bug

Join a group after buff does not appear to automatically anchor to the unit frame
But I can create a group first and then buff it to display normally
```
!Dwv4UTTnq43LaeGKcexz7e3KHLF4K4SMbhzxt5L)rlgPt2SLI0GIYXEOqVfd9fO)TddO)DpoT75yhjTJvYsashKT1XJF39D3X7OPnPrucNg2SDNGJpIskOKwnA2PrNdo8KdMEuR2DsEZHusoLKA)GGvLgbxcuYGXr9VkShLWknZu6bZnCLSaHyqK8I5c2QiyjUy3KDn8CGy0usszHrL71NvktS2S3(v)AvS)rOsyIQ4cdZavXNwfZk1SjGCrdVQ7bYZQILkZ9qnZazvSgmLA8nit3c9Hg5W3awoNRzw2JWqBT5BT4HrJXb50NZ2dQI)fWyLRNj1507GFg9qqJMphzBE8KSUI5ODND(VObrbuZ1vXnd(XD8E7Slgqz7S)pLP05mZEzcLsVNfYRAgS)RXVVaM78)J50NI29Fgc)r9D(wNNaCHZ3VUtWt6(69kUf4puYQbzzfGHggGD4YeSdFOIlX22Zgefn466TYJNNIXaLuU(noqOqM5j3WtnZOKU4AuBYMbecgZAJFsjJl5fZ8YOOxlkB08PtbTfEOBiDTcN5Zu3DUqjHc6z4gRM74uZAHBvElSaKgszwgFjLm58UKOjKOUJSJU3jhifRSg5arjVfycBekz5W6r3I5GqCv66vw360WtxhkKJpPDh7wLfqVLysr8gy96g2hQbh7KH963hrAZlYuTQCoE1aClgBrUG(T96p8YX9DEtUnbDfaB5Abe5vETkfOHh0mWxMmGwYe)gwEWkknSvhk5oLo9gndj4M7LYu2C8B)9N)(F(1)5p(RV)Lp5cXrW0T3ujum31Ay2mjrWkCLu7cxw)bjwZO361WL(u4wBi4frdZlfgUvWRbTwZ42QHzD1mPokNspp2ds0pcSoCXOXxDXJavW)D4XwA85eXUvyZwB6b76ApPeKAxQ5lUg3LS(w3l14b8qM2EOJH)7rZ4zROKZ7fg1BeIvLSyt184G2byppMdKrx2Tk(JFSk(cDjp1lIvpT6oBttIsO0(McCijSLtOTt(qRSnAT8ITUmdZ17ulA8b54WRIUCu3R7zDNmJp1FQuAzhgfgCsX0aE27C7MYR9pmlRnEI9AqQFwlSvGBELN7UGU(WgjT0FR9e)etby9zXMbijopzDCoJlF5OVF89LH3EUcIShEtckTaRoh2YwYO)7d
```
This bug caused my raid mark WA in the middle after I join group
```
!nBzBVTTnqa4)l9tjang2ozzDalfqnX21bo2gsYlyyzsIw6KerKjniPCsA70V9DhLKTZBlbd7ddXqHI8EJNo(CmOxGFG3QaVe6homwwiv4GP9S)6BFES95j0ttG3dZst1GbF70apMioxQMl5cCLZhm1FGlzezrI8oH3D81qWx2nXGKmiyjQvSHlfAYHAdtzObjYW4sTrUIeOzKh5pUGtcGJsXH6C7y8nJINLbkDD06VDcAyjPJ36c2d47EMhWWyRn1LlHnGW4vMMYVpWl8Chp)qpFhx)wHcR1aJnduUobFIXxPIrrDGxp0(AiKTulvlVsMy3Iwtg49vGvyY35K5kW6eV5dMmPwpBSHAOxdffJt017T2OlTuytohWkkS(x)XQiRPoS6YQO6)sLQQiYovrCrv01oHJnagEWiLSC9vWQLyE5GdRIsK7uQ9VczmROkAftDBv0zvrJaJlJN4ZuzGzSibU)aY0h(Cn5PTQXejTd)mAIEpAMF9SpvfzYbXZTWtIb7g0geF)VEDHF9vS63PorCwtg5neMhlfwH)WybMZszXWn3GF7hnWF80rdDDUAWn3Sy8r7sjCr2yuPWp0PtZo8nCrCotKbjwVyuLWBjVoxE37q4xFLTLk)bLb(tRTQtTptfOqd)F8ZY)6Cwk7FCh9FtsdRTV8fFrbMsLOnKXLAab6aV5tC(9bUHwKiwzfE9m3jxGNLDDgFryDbx4I5x44p4JKLg5oBX8q3zEO4nZJqHCi(2TSfbBf0qlkfnZXknsKnblryMVfA91btMpCXKAP2HeTitI7Ub8RN0sUMEuVU1qw8WGGv8Bi4GGCt7JW9BbyTdIPIrabYKSKBbFvngCF2DnUuif7XjBzOaE2bHCOpwX4I3V0BH9Vp5nuwqZm062Emib2fYAAZGRMd8SCSRv)tc8kKmB3o8OnbmT9allmCAq9miFwHea8)wttCBkLRiltV0Qj1RQGP17BcRguA75tY)g80j3Y(DSTs3RdWEeyI8YWTwii20P54PL4(4jBoZ9YS32A1Rb2ToOA6oi5FbQWqfwyDWlyPdFsvVT(wztQ11AemDx3DF4EZfCnBzbKuxRqBiR1NZuu56xAuH6(bfPp5AdFtInaN2TPOgLXiJ30wp(PUh3fxc)K45o0Pk6h)apkHFHQIUcrYpYz1X2IPJ9T4CCTI15m6sc4fssWUZ2AGsYuDJFy4LtzJo(6ZP9HiLNvxTWfKNRVSsPbT8S1MD1s33EfOUwTs47Twkfc4DrygwZfMqyq)o9oTZPhDYVCu2p1)4tJ)zma2GlFsFsIG)(p
```

**Do you have an error log of what happened?**

no

### To Reproduce

create a smart group aura trigger
set anthor to Unit Frame
Buff yourself first,Then join a group or create a premade group
It's better to try a few more times because it doesn't trigger every time

**Screenshots**

批注 2020-03-20 173650
批注 2020-03-20 180622
批注 2020-03-20 173804
批注 2020-03-20 173824
The following is true
批注 2020-03-20 173714

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

yes

**Which version of WeakAuras are you using?**

2.16.6-49-g5236c74

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**

There seems to be no good version

### Additional Info

```
  ERROR HERE
```

### PR DESCRIPTION
**Pull request by mrbuds**
# Description
Use LibGetFrame's FRAME_UNIT_UPDATE callback for automatic re-anchor with anchor on Unit Frames
- For single auras/clones => Fixes #2051 
- For dynamic groups => replaced previous method that was re-sorting everything, this should improve performance a lot

Use WeakAuras.GetUnitNameplate for all anchors to nameplates => this will do a regression for people using nameplate addons.

# TODO
- ~~Handle region.state.unit's guid changed.~~
- Maybe move region.unitframe_monitor cleaning out of WeakAuras.PerformActions
- More testing.

### CODE REVIEW

File: WeakAuras/WeakAuras.lua [hunk 1]
```diff
@@ -4833,6 +4861,15 @@ function WeakAuras.PerformActions(data, type, region)
     end
     wipe(region.active_glows_hidefunc)
   end
+  if type == "finish" and region.unitframe_monitor then
+    local id = region.id .. region.cloneId or ""
```
Comment (InfusOnWoW) [inline WeakAuras/WeakAuras.lua]: This can be problematic if you have:
a) id: ABC, cloneId D
b) id: A, cloneId BCD

which have the same id.

File: WeakAuras/RegionTypes/DynamicGroup.lua [hunk 2]
```diff
@@ -1044,6 +1053,15 @@ local function modify(parent, region, data)
       controlPoint:SetShown(show)
       controlPoint:SetWidth(regionData.dimensions.width)
       controlPoint:SetHeight(regionData.dimensions.height)
+      if regionData.useAnchorPerUnit and regionData.anchorPerUnit == "UNITFRAME" then
+        local guid = UnitGUID(regionData.region.state.unit)
+        if guid then
+          WeakAuras.dyngroup_unitframe_monitor = WeakAuras.dyngroup_unitframe_monitor or {}
```
Comment (InfusOnWoW) [inline WeakAuras/RegionTypes/DynamicGroup.lua]: Don't you need to ensure that the frame is removed from a potential previous registration? E.g. if the unit changed?

File: WeakAuras/RegionTypes/DynamicGroup.lua [hunk 3]
```diff
@@ -54,6 +54,15 @@ local controlPointFunctions = {
   ["ClearAnchorPoint"] = function(self)
     self.point, self.relativeFrame, self.relativePoint, self.offsetX, self.offsetY = nil, nil, nil, nil, nil
   end,
+  ["ReAnchor"] = function(self, point)
```
Comment (InfusOnWoW) [inline WeakAuras/RegionTypes/DynamicGroup.lua]: The call of Reanchor doesn't include a point.

File: WeakAuras/WeakAuras.lua [hunk 4]
```diff
@@ -4686,33 +4686,61 @@ local function actionGlowStart(actions, frame, id)
...
-          local new_frame = WeakAuras.GetUnitFrame(data.region.state.unit)
-          if new_frame and new_frame ~= data.frame then
-            -- remove previous glow
-            actionGlowStop(data.actions, data.frame, id)
-            -- apply the glow to new_frame
-            data.frame = new_frame
-            actionGlowStart(data.actions, data.frame, id)
-            -- update hidefunc
-            data.region.active_glows_hidefunc[data.frame] = function()
+    if type(glow_frame_monitor) == "table" then
```
Comment (InfusOnWoW) [inline WeakAuras/WeakAuras.lua]: hmm, this callback gives us a update on a frame to guid mapping. Which is not exactly what we would need, if I see that correctly.

E.g. consider a aura with "unit == target", and attached to the target unit frame.
Now, the user changes the target, but the trigger says nothing has changed in the state.
The callback then might notify us that the old target's guid is now e.g. raid15's frame, but we don't want to move the aura, we want it to stay in the target frame.

File: WeakAuras/RegionTypes/DynamicGroup.lua (hunk 3 above)
Comment (mrbuds) [reply WeakAuras/RegionTypes/DynamicGroup.lua]: It does in WeakAuras.lua, the ReAnchor() you find in DynamicGroup.lua is a method of moversizer's frame

File: WeakAuras/WeakAuras.lua [hunk 5]
```diff
@@ -6911,12 +6938,26 @@ local function GetAnchorFrame(region, anchorFrameType, parent, anchorFrameFrame)
...
-    return unit and C_NamePlate.GetNamePlateForUnit(unit)
+    return unit and WeakAuras.GetUnitNameplate(unit)
   end
 
   if (anchorFrameType == "UNITFRAME") then
     local unit = region.state.unit
-    return unit and WeakAuras.GetUnitFrame(unit)
+    if unit then
+      local guid = UnitGUID(unit)
+      if guid then
```
Comment (InfusOnWoW) [inline WeakAuras/WeakAuras.lua]: This looks like a left-over from the old guid->frame mapping
