### PR TITLE
Smallfix

### LINKED ISSUE #3546: UnitFrame glows do not work sometimes even though %unit is valid
### Description

https://wago.io/QN3xUbh7

https://user-images.githubusercontent.com/16741112/159385238-7093575c-472f-496d-a686-9b082c075c1a.mp4

Converting to party, dismissing and summoning a pet, and moving players between groups sometimes causes glows to disappear even though %unit is still valid. Video and linked aura show one such example. You'll also notice Rev was inactive in party, probably trying to access raidPetN still or something? Then is not glowed when made a raid but the clone is active again

### WeakAuras Version

WeakAuras 3.7.13

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

_No response_

### Reproduction Steps

1. Create SmartBuff - Auto Clone - Any aura that glows unitframes from %unit, pets and players enabled
2. Convert to party
3. Convert to raid

1. Create SmartBuff - Auto Clone - Any aura that glows unitframes from %unit, players enabled
2. Move players between groups a few times, making sure to have a mix of players who should be glowed or not glowed
3. Move players to G1
4. Convert to party
5. Convert to raid

Also occurs with pet summons, etc 

### Last Good Version

_No response_

### Screenshots

_No response_

### Export String

!WA:2!1vv3UTTnu46Pv0g1S2uJTGH0UnVmSUUoGKM0LuGUTcy5y36o7exz5KoGn4qjszXnkrvsQeNCPrXqV2pc(6DLFek2dWbb7jipc5ID9iLC7k6p3iD4HhD(978PsHLJlJll9VZk3DL1Utz8ZxxC0oHHsI6VlloGiKuEI1uAsixeJu6d2teKb63EhLsEb(OeumnyGGNLogLqlmztNyenPHJsBItcpHCcotKFtFJkHKeWtWYreKKyCdy)cJyxLGKmqfDbxPcjunG5aB4sW8WhPFF5l4hstOYO3uTlJgtvxASKWc7WPjkH3oDAvVH36zcw61IuQu59wD1drd4Rq5R(4TVZWE(r3LS6AJrIGw5r8zloktsAzCu0uFUate14mU4rLkvYAsHI64bK0R29PzibPsJmgRYErufruu1KOtqzQiUyNutDkTfdl6IZFtFtOBU14xfzFbctZKpBEFDBiKoWE9mkEkF4tRvRXoBKDC7zrSl9yY5NeQdvnQiGr2Fzk(K6drXPmsLhyA5tu8GzZOl25tNiZ8DZNns7t8rb)bwWtlQdllRow3ELnot3FiIeeB3IVI4xeQiHULpyaruYvMIciN)0c9oZ8s6com6XhJe4kECotrtDLbigX6ff2vuRZDQUG0okr1afO4cF3QB1SxxFjjwNLURTYTx52osUqb2tdfOyZehPqwJe8d7AcRrsLduknXarOZ6LAVze20rJau2WvSHfSNIsc0978rUFT6B7v3D2ORzIoxSMgWzzXjf(1HXr4g(kDkNOw0notxc2UbmKuUiuZ2rQB1fcPKaJGlIrhKa3FKsqn9f5s3yCwYSd2Izc)5iT9mwtS0gMZfPb5R7KPtr)ug6iDftoqho)hsqmv0emXplm0G3fpSERon616u9al3KU6lOdN2Vw1UE976v117vx1rq0x52Tt9wTC1lBeP9Obck24NL3YDSrEpkwfDjh9w4HopWT5wNv0AAyAXg787wZTE9TlFW)8KYbl98BbFqjn6rXOj6jxpVwn3UoyzbFODAfmvAYDpYqv)Iv((P9v0yYStLorgHW8d)LIj(1ph8RWVbxyt4IV5EjCL3sZcVLMY(o745TtB4JHpb(SsW3dBax3g(HnHFupM3D6ag)W(ftFhze)Wt1RP9ZvgyW1rNLlNJLYPwg3B7MEnCR2U(48Bm6C7qhsycmp)d3hwyXtJOysFeJLRrUp8L2PF17VYtfKaAopi85Wx4g8YnkR0fcYKkES5B6LI1SaWoWTiJoudd3tGshT3mb4NG7l(DTT0WJCmCttl6I)pjdS80nwFTN2w8TBeV5W0V79NnZOC7RIeeDlHHpc(g9YpCxRPV2hn(Rn4WT19f4MlTim3jA8KHsWWuNGH7zFQMUIBORdYrpov1htx(De2x6NzNb70R9otUcbxtoINOHSKcy5ZMhQUl0WStb1ZFUv(thZZXMXzIgNlICc5jQ0fAiOhx5XziSHyOINh8WlFdOPn8O)vZTe7RrSDiIE6uAFOTB(VD0)BkGLH16vYt7KV3jRMGnhHhdUttlSVnhtMKLGcdjbkcwOJSPQ2xJiBn2S5MVBT0jBroGBGBvQQ1b)Sn0d2vpv7a7zdDbVZmz8RfX9NyGL1yAQu5(Px1avpG4vWoyc5FDUzlmpPyHXsZHNETxsIZdRODsLhOrHv6i4(msmCEhLUVoY0om)aOTbZ9F

### PR DESCRIPTION
**Pull request by mrbuds**
Glow commit fixes https://github.com/WeakAuras/WeakAuras2/issues/3546 combined with an update on LibGetFrame https://github.com/mrbuds/LibGetFrame/commit/89a3d7248997cd868a1d778113363ccc38fef192

Tests made to fix #3546 has show 1 or 2 issues in aura trigger not making clones for pet on login or when going converting raid to party, see https://github.com/WeakAuras/WeakAuras2/issues/3755

New icon for "Premade Auras" (ex-"From Templates")
image

I'm not that happy with the icon.. (i liked halloween icon but not available on vanilla) but i think changing icon may help catch some eyes to give it a look

### CODE REVIEW

**Review by Stanzilla — APPROVED** [review]

File: WeakAuras/WeakAuras.lua [hunk 1]
```diff
@@ -3185,51 +3188,60 @@ function Private.HandleGlowAction(actions, region)
...
-        if region.active_glows_hidefunc
-        and region.active_glows_hidefunc[glow_frame]
-        then
-          region.active_glows_hidefunc[glow_frame]()
+        if glow_frame then
+          if region.active_glows_hidefunc
+          and region.active_glows_hidefunc[glow_frame]
+          then
+            region.active_glows_hidefunc[glow_frame]()
+          end
```
Comment (InfusOnWoW) [inline WeakAuras/WeakAuras.lua:3223]: I have not looked to deep into it, but should the hiding of the old frame glow depend on figuring out the new frame?
Or should this code be moved outside the if glow_frame check?

I see that it was previously guarded by the same check, so keeping it that way is probably fine. But it looks a bit odd to me,

Comment (mrbuds) [reply WeakAuras/WeakAuras.lua:3223]: Problem of running this hide glow function outside of the `if glow_frame` check is that a region can apply a glow to multiple frames at once, so which one should be stop?

This code block is only to avoid having 2 different glow applied on the same frame by same region, hide glow func only support one glow per frame/region
