### PR TITLE
Misc

### LINKED ISSUE #1083: Converting a region doesn't make it show in options
**Describe the bug**
I expected the region to show after converting it but instead it's invisible.
It only shows if it triggers outside of /wa

**Do you have an error log of what happened?**
no error

**To Reproduce**
1. Create an icon and convert it to a bar
2. the bar won't show

**Screenshots**
https://i.gyazo.com/e5c8173a8dc7315636055f1e67f982e3.gif

**Which version of WeakAuras are you using?**
2.11.0-Beta1

**Was it working in a previous version? If yes, which was the last good one?**
don't know

### PR DESCRIPTION
**Pull request by emptyrivers**
# Description

Fixes #1083 and removes some new feature indicators which have been around for about 4 months.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Housekeeping (chore which needs to be done, but isn't specifically a fix or new feature)
# How Has This Been Tested?

1. Create any non-group aura.
2. Convert the aura to any other type.
3. Note that the region is correctly shown.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

File: WeakAurasOptions/WeakAurasOptions.lua [hunk 1]
```diff
@@ -3849,10 +3849,13 @@ function WeakAuras.ConvertDisplay(data, newType)
   -- thumbnails[id].region:SetScript("OnUpdate", nil);
   thumbnails[id].region:Hide();
   thumbnails[id] = nil;
+  local visibility = displayButtons[id].view.visibility
```
Comment (InfusOnWoW) [inline WeakAurasOptions/WeakAurasOptions.lua]: displayButtons[id]:GetVisibility()

**Comment by Stanzilla** [comment]
I'm probably for leaving the indicator on the Templates feature for a bit longer, otherwise 👍

**Comment by emptyrivers** [comment]
How much longer? And can you note that in the original ticket?

**Comment by Stanzilla** [comment]
> How much longer? And can you note that in the original ticket?

Done
