### PR TITLE
fix stance trigger on retail

### LINKED ISSUE #1522: Single-selection form/stance trigger not working correctly
**Describe the bug**
An aura with two triggers, with Required for Activation set to All Triggers
(1) Spell Cooldown (always)
(2) Status -> Stance/Form/Aura -> Cat Form

If the selection on trigger 2 is single, the trigger doesn't work and the aura displays when not in cat form. If I change the selection to Multiple and then only choose the cat form box, it works properly. The single selection will work if I check the inverse box, although I was under the impression from the aura working normally in previous releases that inverse meant "not"

**Do you have an error log of what happened?**
No errors in buggrabber

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Not yet

**Which version of WeakAuras are you using?**
2.14.0-beta1

**Was it working in a previous version? If yes, which was the last good one?**
Yes, was working in 2.13.4

**Additional context**

``` !9I1EZPnss8Vlu1wfC3gciSZLKQYvfyJ34emqXGZfxxTc0JbywlRrRMrgZ(h8z)6UNrV4rs27Q9k7sinQNU)1pNULBx35UmH74U9EJtVUUmLlZPD3lA35v(CThSWtUSq8FGS1rYTU(USDtwTsX1UJ74Y8Id2itNkfXAx2GjZNp5UrdVbioqkJcLBJzBfjCCxbzkT8P58x03Ne6P5USm7V5KomCnrPiqg7oaEVIJI8kzKmLwpwZtJ9I(cpvjasg701aQVwbqkE0QAWz2T)Yhb8OLbpNVV32XPdqAix5PZsrm4ByKruZbZb9VdDThD9c8kWuvM)m(AGnkdDiRbDAHAJxyDKO3bkosp(ElvMB)jL9XGkYRt73509Y382348pU4YoV7TK4pEXENAXCWrmDLev(RLPc10P1qxv1RJH)ggEahmu)qvDHwU002)(5tSR(Sqj8J4OdJEUweXTJhpC2I5tMA9cMxwLZPsn4aMt2LXtgpSIsWe)bhGvru2xpeqirZjR8K7Np6wyZAuh2WfR3aKDXfUSKu56uUsnnLhimEFy1iPhfrdryls4AFpToIccWfI5qGc(qeCt0czchcra7g7F(bdbbrEkfQVPEbCKnpLfPfWnK0PD5YEl46r8F4R1Er8yTZrRJm2Sv)CIqAuI41a0aFvb5GJAaUWGYn(mFJiWObQeEq1n2RYgX9aly3iqqQml5iKekwTseaRS7KGeequ0JXq(Qnhnx63lq5N8Csj6RT5uz0XMJvEbA0RC46vKY4lDWeDJvVuZyxp7(BVUCBSP9h1)6BhBvpTjJEKiMRGmEZt3KY)9mECWomjY5sS0tCOqxlBoydp4rkTovSEnejalZE2lv4Hr5GvtLH2hbOIZ4kzwAaiaGGOmUnhkyJx8AEjhnV740UkvvGWuimdS4mtjbJgm250a6vovru)XxBjQsjPtIDYOEB8meEfqUtHG(tPWYeiHOgt0FpDV7Pl5CgDV3z09daxG8ji9TgqoliSNbb1tGQ(l4Xp3oLkL)Egx3pkzJxZoTVS1byI2sGmKNdSl(VcyD)FdyD)EWsJvjfp5LNnP0EPMkibq64nzXbUS9ln)TcEcPRzE1XFE)sI(VMFZd4n4g)A(np0A)NY3p(xKewD)spmxC)YpSFzbZ2V8VTFPdDfGZM2jIw7x(kGa7t7x(A49hWUuoCsCCom2V8Vd030SdiFVjjMw0YDB9AyZi3BAqiX8UTAvG9)m7(H8DxchECO5bB9oKmSuhfD2NYoOB)f6wZP8XYyUD5b0YjGLGJ1X2KkIFe8nOxKo5ke74aDsSoTHIZ7OfFHUs7FgTFsQMZ2sYIu8Y9TW2xbhRDPYpa107dUjGvDB7yFyN5baip5jIlchE5iOxqDnuSRgITsoLhbp(mVQsvX2qlAqoD7ud8RyBQy9ik(bdoHFd5rAV)pgi(JfjDiQQea9sLECoW73TtNFYeHzmJ(0XHIyHAZFHPTNkpRM9QAsLHOJYSob9pus)d)i5svcsu6upQFT)6croHpTMo8nCGL(Nb1skZrnJ0OI0NoNjPOAw(5sKRK3DqnItKI3Pw6Br7ogW5NP1Y4jqBSrE7SVaAr7rOvif1)RsdpT76CP4tncTsSMc8OMeGz(mTD9iFNVigE8cZrmyJ43K69eNU4Y(xCVh7dms9(PYT809l7tKGLjWtWmaIMOJzA1tv90PQH8ulPc6mRq5c7jIdkpB0MONsj5hCqj4U(Ky1(LXsW)M2gNo4ZgGVFPEdpU03A5snka(L((Rs5Gr(gCUd4m941nJfrq8uJjFz4Sr9FOrL4JdeWhQZUttgEu(NanrSA3hB2Ggh6SSScTFPzJ7U96RhnejMIlpIseYnhj8z6m)MnWB24LYdVJhk8EvV2DA0693W1bBA2aNxQbQt2HdBGz2D7qAPzakukhjaC4mA0XM4KNo)C1RDp1gOH)A2iFSpuKh4Vqrw91VYbVC5XmBJCBZZHPMfm1e922gR2YKpSveQ3yMc0MtA)CbJ4XRX3Gtw(sLzkX3vD00GV)xd4pKqKPHwZ3WaX11cf2eyiMx5LPLyqmYBtTcefciFITbCsebq6YKK6dHyYTfXjzAkfSsAPvTWQe8vEWWpUmCOZsvkMYlzi97xItib1WSQSFzV(hjGIe9VPaUmN)FoN8sUBNRCfwyaYH80E0CRvQzyQgWgoA4vZVzw)7gw0)8XJUyhpFnpMNkcWaHj0eN1xaAWsUTF0wVDkd9zyjKbi29HXwmc8Jdhn9M7hv8jzGQPzkJIOmfEYWH(Xpyb5Vyetyjq1taivpZ2LzP7kR)E)YPfNK0KS5Tm4G)cuUZmS8y0G5Jve9IyflKhaumtnT6GcpTfzQmFsKmCiSxCzlUQpB(c28(ZMx(YPPC6LSPdhnYEOLVsM6FhoGGDmDWJaJSKlasAMrRj9VIz)8wy9rZkA9sRKPuT6VjApgwwJjtdXi8xFdWKxJNLCOdOQF9mQCnFeHMZ8Xtk)Uj1D51dnqjkIXpyi30ywvdK9RKO(nQnetJWrfFGtdzJKRfqhlfDQy3Drf)8wsSR)V7(RylSHLl48Ru9EZPMpZTSLmCMspzyrKRMY39UFFRAyidZMZbmI)5qeQwKGp9iNN0h)Wq6zOrcxcGpADVLoy2P3BCUSxzrS8cwdKPH0NcdhJfe7fuWI7)5p ```

### PR DESCRIPTION
**Pull request by mrbuds**
# Description

Fixes #1522

### CODE REVIEW

File: WeakAuras/Prototypes.lua [hunk 1]
```diff
@@ -4340,17 +4340,18 @@ WeakAuras.event_prototypes = {
       if trigger.use_form and trigger.form.single then
         -- Single selection
         ret = ret .. [[
+          local triggger_form = %d
```
Comment (emptyrivers) [inline WeakAuras/Prototypes.lua]: It’s usually spelled trigger, no?

Comment (Stanzilla) [reply WeakAuras/Prototypes.lua]: :D
