### PR TITLE
TSUHelper: hide __changed from pairs()

### LINKED ISSUE #5825: key "__changed" gets looped through when running pairs(allstates)
### Is there an existing issue for this?

- [x] I have searched the existing open and closed issues.

### Description

judging from the helper function PR discussion this isn't the expected behaviour

### WeakAuras Version

5.19.8

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Lua Error

```Text

```

### Reproduction Steps

1. create state using allstates:Update
2. do a pairs(allstates) for loop

### Last Good Version

_No response_

### Screenshots

Image

### Export String

```Text
!WA:2!DnvWUnXouuQksiSQkIiuHLJYcuRuAEqq0sRuxKPnrTsHKiptb2v5z8DYy98ypY2tAdi2u1fSUFczhsiwKf8bWxWOk(cyhB7xa2tkPc8gFNJp3ZCVxF8sDRLvJwJ(PhFfPWKkvdYnmPqJutgKKObZsZiIyl(qjtyI2Vt)Wo4Pgz8yqPTeFYsF9rrXsrcBeAgtKivzeNaifjUsOTWAdrzqrjmbtNI8TBg05gfB0iReR(u1nHFZ3mjhIIl0gz2p1frWyqyckssyNn7K9BheEsqyBCiUcp6qGWnPl4nubwE4GHD61R8b5)kPqu9)xNW52cWa6gv8A0SzZnqE2flXRcXBV98Qpyy4rd6hu3ZKcIQJDRf5U7X5u7(61ZMe4aQ34dwuBQEgvb8XnwKHT)9yn80EmHxoHP03()3WJkxWZToaghkL8DBtPhqmK11ny3keiOlI)7G)CcYfGqNRZbo)iQg5xyNSr5CYeqHJtH4)VSgwqYanA28P6jUj8SQYPOQHMsHi7ao0cRoStVHDpU3LfIBUqq5p0DhogcN)9RLu4l3bFkJAsVyLRT2bqji83m3i8z1z3yyUud8Kk7s5DRZO4(WPETMLOSvsGrz70LXeEEkz5RN7S66oXvcrb7J70P)LebBUjARY7397ar7YdeJmP3RCvFHuaxrluvmQ6iLgSoqQ(ChvNqLB6NryIULnSjuUzzZY)R8z2D0)I0QGrN9cLOLUTS1B3gMATtyyu1dGOuGnk1CXktDIZM)QWNlj0U(A27H1WzfCddHJ5eTETYDq(2RIyxqKHWTolx4uvLCUQcdz5Mj10x9YMpFNMVAtW28BUDTX)4D)(d
```

### Bisector Report

```Text

```

### PR DESCRIPTION
**Pull request by mrbuds**
this is achieved by saving the information in an external table `changedStates`

also add functions to the states table: IsChanged() and SetChanged()

fixes #5825

### CODE REVIEW

File: WeakAuras/TSUHelpers.lua [hunk 1]
```diff
@@ -140,12 +140,41 @@ local createOrReplace = function(states, key, newState)
   end
 end
 
+local isChanged = function(states)
+  return states.__changed == true
+end
+
+local setChanged = function(states, changed)
+  states.__changed = changed
```
Comment (InfusOnWoW) [inline WeakAuras/TSUHelpers.lua:148]: If directly set "changedStates" here instead of in newIndex, and change the checking code to call IsChanged(), you don't need to do change "__index" and "__newIndex"

Comment (mrbuds) [reply WeakAuras/TSUHelpers.lua]: Indeed, it's better

File: WeakAuras/TSUHelpers.lua [hunk 2]
```diff
@@ -140,12 +140,22 @@ local createOrReplace = function(states, key, newState)
...
+local isChanged = function(states)
+  return changedStates[states] == true
+end
+
+local setChanged = function(states, changed)
+  changedStates[states] = changed
+end
+
 Private.allstatesMetatable = {
-  __index = {
```
Comment (InfusOnWoW) [inline WeakAuras/TSUHelpers.lua:144]: Eh you removed the __index here

File: WeakAuras/GenericTrigger.lua [hunk 3]
```diff
@@ -670,10 +670,12 @@ local function RunTriggerFunc(allStates, data, id, triggernum, event, arg1, arg2
       else
         ok, returnValue = xpcall(data.triggerFunc, errorHandler, allStates, event, arg1, arg2, ...);
       end
-      if (ok and (returnValue or (returnValue ~= false and allStates.__changed))) then
+      if (ok and (returnValue or (returnValue ~= false and allStates.IsChanged and allStates:IsChanged()))) then
```
Comment (InfusOnWoW) [inline WeakAuras/GenericTrigger.lua:673]: I think you can just call IsChanged here.

Comment (mrbuds) [reply WeakAuras/GenericTrigger.lua]: i was solving an error caused by the __index mistake

**Review by InfusOnWoW — APPROVED** [review]
