### PR TITLE
wrath templates (WIP)

### LINKED ISSUE #3716: cannot open Model Viewer in latest WeakAuras version for Woltk Beta
### Description

I cannot open Model Viewer in latest WeakAuras version for Woltk Beta. Deleted already full WTF folder and disabled every other addon.
https://streamable.com/wbqgj9

### WeakAuras Version

WeakAuras 4.0.2-32-gd044d71-wrath

### World of Warcraft Flavor

Classic

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

Message: ...ddOns\WeakAurasOptions\OptionsFrames\ModelPicker.lua:43: bad argument #1 to 'ipairs' (table expected, got nil)
Time: Wed Jul 27 11:59:08 2022
Count: 1
Stack: ...ddOns\WeakAurasOptions\OptionsFrames\ModelPicker.lua:43: bad argument #1 to 'ipairs' (table expected, got nil)
[string "=[C]"]: in function `ipairs'
[string "@Interface\AddOns\WeakAurasOptions\OptionsFrames\ModelPicker.lua"]:43: in function <...ddOns\WeakAurasOptions\OptionsFrames\ModelPicker.lua:42>
[string "@Interface\AddOns\WeakAurasOptions\OptionsFrames\ModelPicker.lua"]:63: in function <...ddOns\WeakAurasOptions\OptionsFrames\ModelPicker.lua:60>

Locals: (*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

### Reproduction Steps

1. download latest wotlk beta WA version
2. open WA, create model
3. go into Display tab and click the file icon to get int othe model viewer 

### Last Good Version

works with 4.0.2bcc

### Screenshots

_No response_

### Export String

_No response_

### PR DESCRIPTION
**Pull request by mrbuds**
Fixes #3716

TODO:
- review from peoples who knows more than me about wotlk
- deathknight was half copy pasta from retail to not start from scratch, but it's big WIP

### CODE REVIEW

**Comment by mrbuds** [comment]
Added a fix for https://github.com/WeakAuras/WeakAuras2/issues/3672
image
bottom => no "set parent to anchor"
top => same aura with "set parent to anchor"

**Comment by mrbuds** [comment]
@emptyrivers about https://github.com/WeakAuras/WeakAuras2/pull/3712/commits/0778df22cff72f8f1696a52b34c9c54ed9ce747c do you want it or not, or done differently?
I'm not a fan of adding a new toggle as the issue ticket proposed.

File: WeakAuras/RegionTypes/DynamicGroup.lua [hunk 1]
```diff
@@ -1084,6 +1084,9 @@ local function modify(parent, region, data)
       controlPoint:SetShown(show and frame ~= WeakAuras.HiddenFrames)
       controlPoint:SetWidth(regionData.dimensions.width)
       controlPoint:SetHeight(regionData.dimensions.height)
+      if data.anchorFrameParent then
+        controlPoint:SetParent(frame)
+      end
```
Comment (InfusOnWoW) [inline WeakAuras/RegionTypes/DynamicGroup.lua:1089]: You need to SetParent in the else case too.

Otherwise if a dynamic group that was previously set anchorFrameParent to true, will not work correctly once the options is disabled.
