### PR TITLE
Fix and migration of textures & models for 8.2 API changes

### LINKED ISSUE #1291: [8.2 PTR] Texture path changed ?
Animated icons from menu for "texture" and "progress texture" have missing textures

img

### PR DESCRIPTION
**Pull request by mrbuds**
# Description
Fixes #1291
SetTexture() can't use internal Path like "Texture/...." and need an id instead.
I replaced path for some textures with what the function GetFileIDFromPath() return on live, and fixed texture browser to handle numbers.

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
- [x] Test on live
- [x] Test on 8.2 ptr

# TODO
- [x] Test everything on PTR (currently down)

Model browser is still broken, all path in the file "ModelPaths.lua" has to be replaced by ids.
Afaik all ids can be found in https://raw.githubusercontent.com/Resike/BlizzardInterfaceResources/b6abf3b3b320a2a2f1054f20ddd17df6b1a0404c/Resources/Data/CreatureDisplayPath.lua
But i'd like @InfusOnWoW on the matter first because you are the last one who edited the file, from a list submited on reddit from what you wrote on commit message, and the whole list might needs an update.

### CODE REVIEW

**Comment by emptyrivers** [comment]
7.2 PTR was over a year ago, so I think this is a bit late ;)

**Comment by mrbuds** [comment]
shit too late :(

**Comment by Stanzilla** [comment]
So for all the upcoming changes for file name to id stuff, I want the original file name as a comment next to it, just so it is clear what it is from just reading the code

File: WeakAuras/Types.lua [hunk 1]
```diff
@@ -880,15 +879,15 @@ WeakAuras.texture_types = {
...
+    [130877] = "Blizzard Spark",
     ["Insanity-Spark"] = "Blizzard Insanity Spark",
     ["XPBarAnim-OrangeSpark"] = "Blizzard XPBar Spark",
     ["GarrMission_EncounterBar-Spark"] = "Blizzard Garrison Mission Encounter Spark",
     ["Legionfall_BarSpark"]= "Blizzard Legionfall Spark",
     ["honorsystem-bar-spark"] = "Blizzard Honor System Spark",
     ["bonusobjectives-bar-spark"] = "Bonus Objectives Spark",
-    ["worldstate-capturebar-spark-green"] = "Capture Bar Green Spark",
-    ["worldstate-capturebar-spark-yellow"] = "Capture Bar Yellow Spark"
+    -- ["worldstate-capturebar-spark-green"] = "Capture Bar Green Spark", -- removed in 7.2
```
Comment (Stanzilla) [inline WeakAuras/Types.lua]: GetBuildInfo() check if you want

**Comment by InfusOnWoW** [comment]
I only update the ModelPaths.lua file if someone asks for a update, so it's almost always out of date. The commit message does link to a small C++ utility I wrote to generate the file, and I can adjust that to read in the file that you posted, but:

* That list does not include the spells directory
* And what should we do in the future, when we no longer get file names?

**Comment by mrbuds** [comment]
added a fix for texture/progressTexture input widget not working with numbers
added a migrations for textures

models migrations & browser are still TODO

**Comment by mrbuds** [comment]
Added a temporary file that will replace ModelPaths.lua after 8.2 is out
Made with the following addon: [WAModelIds.zip](https://github.com/WeakAuras/WeakAuras2/files/3110110/WAModelIds.zip)

File: WeakAuras/WeakAuras.lua [hunk 2]
```diff
@@ -2868,6 +2872,38 @@ function WeakAuras.Modernize(data)
...
+      if type(data.backgroundTexture) == "string" then
+        local textureId = GetFileIDFromPath(data.backgroundTexture:gsub("\\\\", "\\"))
+        if textureId and textureId > 0 then
+          data.backgroundTexture = tostring(textureId)
+        end
+      end
+    end
+  end
+
+  if data.regionType == "model" and WeakAuras.BuildInfo <= 80100 and not data.model_fileId then -- prepare for migration at 8.2
```
Comment (mrbuds) [inline WeakAuras/WeakAuras.lua]: model_fileId cannot be automatically populated after 8.2

File: WeakAuras/WeakAuras.lua [hunk 3]
```diff
@@ -5572,3 +5608,21 @@ function WeakAuras.FindUnusedId(prefix)
...
+    if WoW82 then
+      pcall(function() frame:SetModel(tonumber(data)) end)
+    else
+      pcall(function() frame:SetDisplayInfo(tonumber(data)) end)
+    end
+  else
+    if isUnit then
+      pcall(function() frame:SetUnit(data) end)
+    else
+      pcall(function() frame:SetModel(data) end)
```
Comment (mrbuds) [inline WeakAuras/WeakAuras.lua]: all model setters are wrapped with pcall to not show lua error on bad inputs

File: WeakAurasOptions/AceGUI-Widgets/AceGUIContainer-WeakAurasTreeGroup.lua [hunk 4]
```diff
@@ -0,0 +1,719 @@
...
+	line.text = v.text
+	line.icon = v.icon
+	line.iconCoords = v.iconCoords
+	line.disabled = v.disabled
+	line.tree = tree
+	line.level = level
+	line.parent = parent
+	line.visible = v.visible
+	line.uniquevalue = GetButtonUniqueValue(line)
+	line.fileId = v.fileId
```
Comment (mrbuds) [inline WeakAurasOptions/AceGUI-Widgets/AceGUIContainer-WeakAurasTreeGroup.lua]: read new fileId property added to ModelPaths.lua

File: WeakAurasOptions/AceGUI-Widgets/AceGUIContainer-WeakAurasTreeGroup.lua [hunk 5]
```diff
@@ -0,0 +1,719 @@
...
+			buttonnum = buttonnum + 1
+		end
+
+	end,
+
+	["SetSelected"] = function(self, value, fileId)
+		local status = self.status or self.localstatus
+		if status.selected ~= value then
+			status.selected = value
+			self:Fire("OnGroupSelected", value, fileId)
```
Comment (mrbuds) [inline WeakAurasOptions/AceGUI-Widgets/AceGUIContainer-WeakAurasTreeGroup.lua]: return value and fileId on "OnGroupSelected" event

File: WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasTextureButton.lua [hunk 6]
```diff
@@ -112,7 +112,7 @@ local function Constructor()
   texture:SetPoint("BOTTOMLEFT", button, 4, 4);
   texture:SetPoint("TOPRIGHT", button, -4, -4);
 
-  button:SetScript("OnEnter", function() Show_Tooltip(button, texture.name, texture.path:gsub("\\", "\n")) end);
+  button:SetScript("OnEnter", function() Show_Tooltip(button, texture.name, type(texture.path) == "string" and texture.path:gsub("\\", "\n") or texture.path) end);
```
Comment (mrbuds) [inline WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasTextureButton.lua]: i added a string type check because previously i migrated texture.path to a number, but reverted it, and i still had some data with type == "number"
this can be safely reverted

File: WeakAurasOptions/OptionsFrames/TexturePicker.lua [hunk 7]
```diff
@@ -159,8 +159,10 @@ local function ConstructTexturePicker(frame)
     frame.window = "texture";
     local picked = false;
     local _, givenPath
-    if(type(self.givenPath) == "string") then
+    if type(self.givenPath) == "string" then
       givenPath = self.givenPath;
+    elseif type(self.givenPath) == "number" then
```
Comment (mrbuds) [inline WeakAurasOptions/OptionsFrames/TexturePicker.lua]: same here can be reverted

File: WeakAurasOptions/RegionOptions/Model.lua [hunk 8]
```diff
@@ -188,6 +182,22 @@ local function createOptions(id, data)
     },
   };
 
+  if WeakAuras.BuildInfo > 80100 then
```
Comment (mrbuds) [inline WeakAurasOptions/RegionOptions/Model.lua]: region option switch to model_fileId after 8.2

File: WeakAuras/WeakAuras.lua [hunk 9]
```diff
@@ -2868,6 +2872,38 @@ function WeakAuras.Modernize(data)
...
+      end
+    end
+  end
+
+  if data.regionType == "model" and WeakAuras.BuildInfo <= 80100 and not data.model_fileId then -- prepare for migration at 8.2
+    WeakAuras.SetModel(modelMigration, data.model_path, data.model_fileId)
+    local modelId = modelMigration:GetModelFileID()
+    if modelId then
+      data.model_fileId = tostring(modelId)
+    end
```
Comment (InfusOnWoW) [inline WeakAuras/WeakAuras.lua]:
```suggestion
    elseif data.modelIsUnit then
      data.model_fileId = data.model_path
    end
```

**Comment by mrbuds** [comment]
Migration of models that were using SetDisplayInfo should work fine, WeakAuras.SetModel works as intended with numbers pre 8.2
Your example with old id "136" get converted to model_fileId "122968" which is creature/arthaslichking/arthaslichking.m2 according to https://wow.tools/files/#search=122968&page=1&sort=0&desc=asc
But for a reason i don't know SetDisplayInfo(136) doesn't show anything, i tested with master branch and get the same result, so it's not a new issue from my code.

**Comment by InfusOnWoW** [comment]
I can't test this on the PTR, as it is down atm. I think it should now work, but testing it on the PTR would be good.

**Comment by mrbuds** [comment]
I thought from tests i did that SetDisplay wasn't working anymore in 8.2 but i was wrong, and indeed it doesn't do the exact same thing, good catch.

About the layout i think "animate" toggle should stay on same line as it's slider, but i'm not sure about moving "Portrait Zoom" on the same line as the "SetTransform" toggle.

img

What do you think ?

**Comment by Stanzilla** [comment]
Try it and post before/after screenshots! :P

**Comment by mrbuds** [comment]
before
img

after
img

**Comment by Stanzilla** [comment]
after looks better to me

File: WeakAurasOptions/AceGUI-Widgets/AceGUIContainer-WeakAurasTreeGroup.lua [hunk 10]
```diff
@@ -0,0 +1,719 @@
+--[[-----------------------------------------------------------------------------
+WeakAurasTreeGroup Container
+Container that uses a tree control to switch between groups.
+-------------------------------------------------------------------------------]]
+local Type, Version = "WeakAurasTreeGroup", 41
```
Comment (Stanzilla) [inline WeakAurasOptions/AceGUI-Widgets/AceGUIContainer-WeakAurasTreeGroup.lua]: start with 1 instead of 41 maybe? :D

File: WeakAurasOptions/AceGUI-Widgets/AceGUIContainer-WeakAurasTreeGroup.lua [hunk 11]
```diff
@@ -0,0 +1,719 @@
...
+		status.scrollToSelection = status.scrollToSelection or scrollToSelection	-- needs to be cached in case the control hasn't been drawn yet (code bails out below)
+
+		self:BuildLevel(tree, 1)
+
+		local numlines = #lines
+
+		local maxlines = (floor(((self.treeframe:GetHeight()or 0) - 20 ) / 18))
+		if maxlines <= 0 then return end
+
+		-- workaround for lag spikes on WoW 8.0
```
Comment (Stanzilla) [inline WeakAurasOptions/AceGUI-Widgets/AceGUIContainer-WeakAurasTreeGroup.lua]:
```suggestion
		-- WORKAROUND for lag spikes on WoW 8.0
```

File: WeakAurasOptions/AceGUI-Widgets/AceGUIContainer-WeakAurasTreeGroup.lua [hunk 12]
```diff
@@ -0,0 +1,719 @@
...
+			if scrollToSelection and status.selected then
+				local show
+				for i,line in ipairs(lines) do	-- find the line number
+					if line.uniquevalue==status.selected then
+						show=i
+					end
+				end
+				if not show then
+					-- selection was deleted or something?
+				elseif show>=first and show<=last then
```
Comment (Stanzilla) [inline WeakAurasOptions/AceGUI-Widgets/AceGUIContainer-WeakAurasTreeGroup.lua]:
```suggestion
				elseif show >= first and show <= last then
```

File: WeakAurasOptions/AceGUI-Widgets/AceGUIContainer-WeakAurasTreeGroup.lua [hunk 13]
```diff
@@ -0,0 +1,719 @@
...
+					-- all good
+				else
+					-- scrolling needed!
+					if show<first then
```
Comment (Stanzilla) [inline WeakAurasOptions/AceGUI-Widgets/AceGUIContainer-WeakAurasTreeGroup.lua]:
```suggestion
					if show < first then
```

File: WeakAurasOptions/AceGUI-Widgets/AceGUIContainer-WeakAurasTreeGroup.lua [hunk 14]
```diff
@@ -0,0 +1,719 @@
...
+						status.scrollvalue = show-1
```
Comment (Stanzilla) [inline WeakAurasOptions/AceGUI-Widgets/AceGUIContainer-WeakAurasTreeGroup.lua]:
```suggestion
						status.scrollvalue = show - 1
```

File: WeakAurasOptions/AceGUI-Widgets/AceGUIContainer-WeakAurasTreeGroup.lua [hunk 15]
```diff
@@ -0,0 +1,719 @@
...
+					else
+						status.scrollvalue = show-maxlines
+					end
+					first, last = status.scrollvalue+1, status.scrollvalue + maxlines
```
Comment (Stanzilla) [inline WeakAurasOptions/AceGUI-Widgets/AceGUIContainer-WeakAurasTreeGroup.lua]:
```suggestion
					first, last = status.scrollvalue + 1, status.scrollvalue + maxlines
```

File: WeakAurasOptions/AceGUI-Widgets/AceGUIContainer-WeakAurasTreeGroup.lua [hunk 16]
```diff
@@ -0,0 +1,719 @@
...
+		local buttonnum = 1
+		for i = first, last do
+			local line = lines[i]
+			local button = buttons[buttonnum]
+			if not button then
+				button = self:CreateButton()
+
+				buttons[buttonnum] = button
+				button:SetParent(treeframe)
+				button:SetFrameLevel(treeframe:GetFrameLevel()+1)
```
Comment (Stanzilla) [inline WeakAurasOptions/AceGUI-Widgets/AceGUIContainer-WeakAurasTreeGroup.lua]:
```suggestion
				button:SetFrameLevel(treeframe:GetFrameLevel() + 1)
```

File: WeakAurasOptions/AceGUI-Widgets/AceGUIContainer-WeakAurasTreeGroup.lua [hunk 17]
```diff
@@ -0,0 +1,719 @@
...
+				if buttonnum == 1 then
+					if self.showscroll then
+						button:SetPoint("TOPRIGHT", -22, -10)
+						button:SetPoint("TOPLEFT", 0, -10)
+					else
+						button:SetPoint("TOPRIGHT", 0, -10)
+						button:SetPoint("TOPLEFT", 0, -10)
+					end
+				else
+					button:SetPoint("TOPRIGHT", buttons[buttonnum-1], "BOTTOMRIGHT",0,0)
```
Comment (Stanzilla) [inline WeakAurasOptions/AceGUI-Widgets/AceGUIContainer-WeakAurasTreeGroup.lua]:
```suggestion
					button:SetPoint("TOPRIGHT", buttons[buttonnum - 1], "BOTTOMRIGHT", 0, 0)
```

File: WeakAurasOptions/AceGUI-Widgets/AceGUIContainer-WeakAurasTreeGroup.lua [hunk 18]
```diff
@@ -0,0 +1,719 @@
...
+					button:SetPoint("TOPLEFT", buttons[buttonnum-1], "BOTTOMLEFT",0,0)
```
Comment (Stanzilla) [inline WeakAurasOptions/AceGUI-Widgets/AceGUIContainer-WeakAurasTreeGroup.lua]:
```suggestion
					button:SetPoint("TOPLEFT", buttons[buttonnum - 1], "BOTTOMLEFT", 0, 0)
```

File: WeakAurasOptions/AceGUI-Widgets/AceGUIContainer-WeakAurasTreeGroup.lua [hunk 19]
```diff
@@ -0,0 +1,719 @@
...
+				end
+			end
+
+			UpdateButton(button, line, status.selected == line.uniquevalue, line.hasChildren, groupstatus[line.uniquevalue] )
```
Comment (Stanzilla) [inline WeakAurasOptions/AceGUI-Widgets/AceGUIContainer-WeakAurasTreeGroup.lua]:
```suggestion
			UpdateButton(button, line, status.selected == line.uniquevalue, line.hasChildren, groupstatus[line.uniquevalue])
```

File: WeakAurasOptions/AceGUI-Widgets/AceGUIContainer-WeakAurasTreeGroup.lua [hunk 20]
```diff
@@ -0,0 +1,719 @@
...
+	["SelectByValue"] = function(self, uniquevalue)
+		self:Select(uniquevalue, ("\001"):split(uniquevalue))
+	end,
+
+	["ShowScroll"] = function(self, show)
+		self.showscroll = show
+		if show then
+			self.scrollbar:Show()
+			if self.buttons[1] then
+				self.buttons[1]:SetPoint("TOPRIGHT", self.treeframe,"TOPRIGHT",-22,-10)
```
Comment (Stanzilla) [inline WeakAurasOptions/AceGUI-Widgets/AceGUIContainer-WeakAurasTreeGroup.lua]:
```suggestion
				self.buttons[1]:SetPoint("TOPRIGHT", self.treeframe, "TOPRIGHT", -22, -10)
```

File: WeakAurasOptions/AceGUI-Widgets/AceGUIContainer-WeakAurasTreeGroup.lua [hunk 21]
```diff
@@ -0,0 +1,719 @@
...
+			end
+		else
+			self.scrollbar:Hide()
+			if self.buttons[1] then
+				self.buttons[1]:SetPoint("TOPRIGHT", self.treeframe,"TOPRIGHT",0,-10)
```
Comment (Stanzilla) [inline WeakAurasOptions/AceGUI-Widgets/AceGUIContainer-WeakAurasTreeGroup.lua]:
```suggestion
				self.buttons[1]:SetPoint("TOPRIGHT", self.treeframe, "TOPRIGHT", 0, -10)
```

File: WeakAurasOptions/AceGUI-Widgets/AceGUIContainer-WeakAurasTreeGroup.lua [hunk 22]
```diff
@@ -0,0 +1,719 @@
...
+	dragger:SetScript("OnEnter", Dragger_OnEnter)
+	dragger:SetScript("OnLeave", Dragger_OnLeave)
+	dragger:SetScript("OnMouseDown", Dragger_OnMouseDown)
+	dragger:SetScript("OnMouseUp", Dragger_OnMouseUp)
+
+	local scrollbar = CreateFrame("Slider", ("AceConfigDialogTreeGroup%dScrollBar"):format(num), treeframe, "UIPanelScrollBarTemplate")
+	scrollbar:SetScript("OnValueChanged", nil)
+	scrollbar:SetPoint("TOPRIGHT", -10, -26)
+	scrollbar:SetPoint("BOTTOMRIGHT", -10, 26)
+	scrollbar:SetMinMaxValues(0,0)
```
Comment (Stanzilla) [inline WeakAurasOptions/AceGUI-Widgets/AceGUIContainer-WeakAurasTreeGroup.lua]:
```suggestion
	scrollbar:SetMinMaxValues(0, 0)
```

File: WeakAurasOptions/AceGUI-Widgets/AceGUIContainer-WeakAurasTreeGroup.lua [hunk 23]
```diff
@@ -0,0 +1,719 @@
...
+	scrollbar:SetValueStep(1)
+	scrollbar:SetValue(0)
+	scrollbar:SetWidth(16)
+	scrollbar:SetScript("OnValueChanged", OnScrollValueChanged)
+
+	local scrollbg = scrollbar:CreateTexture(nil, "BACKGROUND")
+	scrollbg:SetAllPoints(scrollbar)
+	scrollbg:SetColorTexture(0,0,0,0.4)
```
Comment (Stanzilla) [inline WeakAurasOptions/AceGUI-Widgets/AceGUIContainer-WeakAurasTreeGroup.lua]:
```suggestion
	scrollbg:SetColorTexture(0, 0, 0, 0.4)
```

File: WeakAurasOptions/AceGUI-Widgets/AceGUIContainer-WeakAurasTreeGroup.lua [hunk 24]
```diff
@@ -0,0 +1,719 @@
...
+
+	local border = CreateFrame("Frame",nil,frame)
```
Comment (Stanzilla) [inline WeakAurasOptions/AceGUI-Widgets/AceGUIContainer-WeakAurasTreeGroup.lua]:
```suggestion
	local border = CreateFrame("Frame", nil, frame)
```

File: WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasTextureButton.lua (hunk 6 above)
Comment (Stanzilla) [reply WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasTextureButton.lua]: revert it!

File: WeakAurasOptions/OptionsFrames/TexturePicker.lua (hunk 7 above)
Comment (Stanzilla) [reply WeakAurasOptions/OptionsFrames/TexturePicker.lua]: do it :)

File: WeakAurasOptions/RegionOptions/Model.lua [hunk 25]
```diff
@@ -188,6 +186,30 @@ local function createOptions(id, data)
...
+    options.modelDisplayInfo = {
+      type = "toggle",
+      width = WeakAuras.normalWidth,
+      name = L["Use Display Info Id"],
+      order = 0.6,
+      hidden = function() return data.modelIsUnit end
+    }
+
```
Comment (Stanzilla) [inline WeakAurasOptions/RegionOptions/Model.lua]: remove space

File: WeakAurasOptions/RegionOptions/Model.lua [hunk 26]
```diff
@@ -265,6 +270,7 @@ end
 local function createIcon()
   local data = {
     model_path = "Creature/Arthaslichking/arthaslichking.m2",
+    model_fileId = "122968",
```
Comment (Stanzilla) [inline WeakAurasOptions/RegionOptions/Model.lua]:
```suggestion
    model_fileId = "122968", -- Creature/Arthaslichking/arthaslichking.m2
```

File: WeakAurasOptions/RegionOptions/Model.lua [hunk 27]
```diff
@@ -296,6 +302,7 @@ local templates = {
       width = 100,
       height = 100,
       model_path = "spells/6fx_smallfire.m2",
+      model_fileId = "937416",
```
Comment (Stanzilla) [inline WeakAurasOptions/RegionOptions/Model.lua]:
```suggestion
      model_fileId = "937416", -- spells/6fx_smallfire.m2
```

File: WeakAurasOptions/RegionOptions/Model.lua [hunk 28]
```diff
@@ -310,6 +317,7 @@ local templates = {
       advance = true,
       sequence = 1,
       model_path = "spells/7fx_druid_halfmoon_missile.m2",
+      model_fileId = "1322288",
```
Comment (Stanzilla) [inline WeakAurasOptions/RegionOptions/Model.lua]:
```suggestion
      model_fileId = "1322288", -- spells/7fx_druid_halfmoon_missile.m2
```

File: WeakAurasOptions/RegionOptions/Model.lua [hunk 29]
```diff
@@ -324,6 +332,7 @@ local templates = {
       advance = true,
       sequence = 1,
       model_path = "spells/proc_arcane_impact_low.m2",
+      model_fileId = "1042743",
```
Comment (Stanzilla) [inline WeakAurasOptions/RegionOptions/Model.lua]:
```suggestion
      model_fileId = "1042743", -- spells/proc_arcane_impact_low.m2
```

File: WeakAurasOptions/RegionOptions/Model.lua [hunk 30]
```diff
@@ -338,6 +347,7 @@ local templates = {
       advance = true,
       sequence = 1,
       model_path = "spells/7fx_godking_orangerune_state.m2",
+      model_fileId = "1307356",
```
Comment (Stanzilla) [inline WeakAurasOptions/RegionOptions/Model.lua]:
```suggestion
      model_fileId = "1307356", -- spells/7fx_godking_orangerune_state.m2
```

File: WeakAurasOptions/RegionOptions/Model.lua [hunk 31]
```diff
@@ -349,6 +359,7 @@ local templates = {
       advance = true,
       sequence = 1,
       model_path = "spells/7fx_godking_bluerune_state.m2",
+      model_fileId = "1307354",
```
Comment (Stanzilla) [inline WeakAurasOptions/RegionOptions/Model.lua]:
```suggestion
      model_fileId = "1307354", -- spells/7fx_godking_bluerune_state.m2
```

File: WeakAurasOptions/RegionOptions/Model.lua [hunk 32]
```diff
@@ -360,6 +371,7 @@ local templates = {
       advance = true,
       sequence = 1,
       model_path = "spells/7fx_godking_yellowrune_state.m2",
+      model_fileId = "1307358",
```
Comment (Stanzilla) [inline WeakAurasOptions/RegionOptions/Model.lua]:
```suggestion
      model_fileId = "1307358", -- spells/7fx_godking_yellowrune_state.m2
```

File: WeakAurasOptions/RegionOptions/Model.lua [hunk 33]
```diff
@@ -371,6 +383,7 @@ local templates = {
       advance = true,
       sequence = 1,
       model_path = "spells/7fx_godking_purplerune_state.m2",
+      model_fileId = "1307355",
```
Comment (Stanzilla) [inline WeakAurasOptions/RegionOptions/Model.lua]:
```suggestion
      model_fileId = "1307355", -- spells/7fx_godking_purplerune_state.m2
```

File: WeakAurasOptions/RegionOptions/Model.lua [hunk 34]
```diff
@@ -382,6 +395,7 @@ local templates = {
       advance = true,
       sequence = 1,
       model_path = "spells/7fx_godking_greenrune_state.m2",
+      model_fileId = "1307357",
```
Comment (Stanzilla) [inline WeakAurasOptions/RegionOptions/Model.lua]:
```suggestion
      model_fileId = "1307357", -- spells/7fx_godking_greenrune_state.m2
```

File: WeakAurasOptions/RegionOptions/ProgressTexture.lua [hunk 35]
```diff
@@ -764,7 +764,7 @@ local templates = {
       xOffset = 0,
       yOffset = 150,
       mirror = true,
-      foregroundTexture = "Textures\\SpellActivationOverlays\\Backlash",
+      foregroundTexture = "460830",
```
Comment (Stanzilla) [inline WeakAurasOptions/RegionOptions/ProgressTexture.lua]:
```suggestion
      foregroundTexture = "460830", -- "Textures\\SpellActivationOverlays\\Backlash"
```

File: WeakAurasOptions/RegionOptions/Texture.lua [hunk 36]
```diff
@@ -182,7 +182,7 @@ local templates = {
   {
     title = L["Star"],
     data = {
-      texture = "Spells\\T_Star3",
+      texture = "241049",
```
Comment (Stanzilla) [inline WeakAurasOptions/RegionOptions/Texture.lua]:
```suggestion
      texture = "241049", -- Spells\\T_Star3
```

File: WeakAurasOptions/RegionOptions/Texture.lua [hunk 37]
```diff
@@ -192,7 +192,7 @@ local templates = {
   {
     title = L["Leaf"],
     data = {
-      texture = "Spells\\Nature_Rune_128",
+      texture = "166606",
```
Comment (Stanzilla) [inline WeakAurasOptions/RegionOptions/Texture.lua]:
```suggestion
      texture = "166606", -- Spells\\Nature_Rune_128
```

File: WeakAurasOptions/RegionOptions/Texture.lua [hunk 38]
```diff
@@ -202,7 +202,7 @@ local templates = {
   {
     title = L["Hawk"],
     data = {
-      texture = "Spells\\Aspect_Hawk",
+      texture = "165609",
```
Comment (Stanzilla) [inline WeakAurasOptions/RegionOptions/Texture.lua]:
```suggestion
      texture = "165609", -- Spells\\Aspect_Hawk
```

File: WeakAurasOptions/WeakAurasOptions.toc [hunk 39]
```diff
@@ -64,3 +64,4 @@ AceGUI-Widgets\AceGUIWidget-WeakAurasNewButton.lua
 AceGUI-Widgets\AceGUIWidget-WeakAurasImportButton.lua
 AceGUI-Widgets\AceGUIWidget-WeakAurasSortedDropDown.lua
 AceGUI-Widgets\AceGUIWidget-WeakAurasTwoColumnDropDown.lua
+AceGUI-Widgets\AceGUIContainer-WeakAurasTreeGroup.lua
```
Comment (Stanzilla) [inline WeakAurasOptions/WeakAurasOptions.toc]: we currently don't use localization that file but add to `babelfish.lua` anyway
