### PR TITLE
don't show raidTarget symbol if index is X > 8, fixes #3473

### LINKED ISSUE #3473: Built in text subregion of raidMark returns text if index of SetRaidTarget > 8
### Description

https://wowpedia.fandom.com/wiki/API_SetRaidTarget
It tells that icon should be invisible if index of SetRaidTarget > 8 , but the builtin text subregion of raidMark returns text as the picture shows.
WowClassic_ezJqngASaF

### WeakAuras Version

3.7.8-1-g9b6154a

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

_No response_

### Reproduction Steps

1. creat a builtin player info trigger
2. add text subregion for %1.raidMark
3. it returns text if index of raidtarget > 8

### Last Good Version

_No response_

### Screenshots

_No response_

### Export String

_No response_

### PR DESCRIPTION
**Pull request by mrbuds**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #(issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by mrbuds** [comment]
added commit to fix an error when using a combat log trigger, text %sourceName with guid+color formatter, it's wrong formatter but shouldn't error.

**Comment by mrbuds** [comment]
added fix for #3477

File: WeakAuras/BuffTrigger2.lua [hunk 1]
```diff
@@ -1198,8 +1198,8 @@ end
 local function markForTriggerInfo(triggerInfo, unit)
   if triggerInfo.fetchRaidMark then
     local rt = GetRaidTargetIndex(unit)
-    if rt then
-      return "{rt" .. GetRaidTargetIndex(unit) .. "}"
+    if rt and rt > 1 and rt < 9 then
```
Comment (emptyrivers) [inline WeakAuras/BuffTrigger2.lua:1201]: i think you should do this, otherwise skull marks will mysteriously vanish
```suggestion
    if rt and rt >= 1 and rt < 9 then
```

Comment (emptyrivers) [reply WeakAuras/BuffTrigger2.lua:1201]: either that or im misremembering how raid target indices work
