### PR TITLE
Filter generic & custom triggers with CLEU and UNIT_* events before xpcall(data.triggerFunc, ...)

### LINKED ISSUE #1324: "Action Usable" trigger doesn't filter "UNIT_POWER_FREQUENT" from others
**Describe the bug**
We had a report on discord from someone who use a lot of Action Usable trigger that went from 85% cpu time used by WA to 5% by replacing those triggers.
His issue was very noticeable while he was in raid and the event most of this CPU time was coming from is UNIT_POWER_FREQUENT.

=============

I didn't found how to modify current trigger to filter without rewriting the whole thing as a TSU: https://hastebin.com/jeyijukoga.rb
This implementation still has a bug where modifying the spell isn't taken into account before a reload

I guess there is an easier and more efficient way to do it, that's why i didn't made a PR

### PR DESCRIPTION
**Pull request by mrbuds**
# Description
Generic triggers register there UNIT_* events with RegisterEvent, where most can be registered with RegisterUnitEvent to filter on trigger.unit and lower the load.

Custom triggers can benefit from it by declaring their UNIT events with the format EVENT:UNIT

[edit] added support for COMBAT_LOG_EVENT_UNFILTERED subevent filtering for custom triggers like it's done for the "Combat Log" generic trigger
Also added CLEU as an alias for COMBAT_LOG_EVENT_UNFILTERED 

Examples of new possible syntax for custom triggers with events:
```
UNIT_TARGET:boss1:boss2:boss3:boss4:boss5
UNIT_SPELLCAST_SUCCEEDED:player:target
COMBAT_LOG_EVENT_UNFILTERED:SPELL_CAST_START
CLEU:SPELL_CAST_START:SPELL_AURA_APPLIED
```

Fixes #1324 and partially #1332

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# TODO:
- [x] Allow custom code to use per unit events
- [ ] and document it
- [x] Self-review
- [x] Check if CLEU subevents typed are valid

### CODE REVIEW

File: WeakAuras/Types.lua [hunk 1]
```diff
@@ -1953,3 +1953,26 @@ WeakAuras.font_sizes = {
...
+-- unitIds registerable with RegisterUnitEvent
+WeakAuras.baseUnitId = {
+  ["player"] = true,
+  ["target"] = true,
+  ["pet"] = true,
+  ["focus"] = true,
+  ["vehicle"] = true
+  -- ["mouseover"] = true
+}
+for i=1,4 do
```
Comment (Stanzilla) [inline WeakAuras/Types.lua]:
```suggestion

for i=1,4 do
```

File: WeakAuras/Types.lua [hunk 2]
```diff
@@ -1953,3 +1953,26 @@ WeakAuras.font_sizes = {
...
+  WeakAuras.baseUnitId["party"..i] = true
+  WeakAuras.baseUnitId["partypet"..i] = true
+end
+for i=1,5 do
```
Comment (Stanzilla) [inline WeakAuras/Types.lua]:
```suggestion

for i=1,5 do
```

File: WeakAuras/Types.lua [hunk 3]
```diff
@@ -1953,3 +1953,26 @@ WeakAuras.font_sizes = {
...
+  WeakAuras.baseUnitId["arena"..i] = true
+  WeakAuras.baseUnitId["boss"..i] = true
+end
+for i=1,40 do
```
Comment (Stanzilla) [inline WeakAuras/Types.lua]:
```suggestion

for i=1,40 do
```

File: WeakAuras/GenericTrigger.lua [hunk 4]
```diff
@@ -824,15 +900,32 @@ function GenericTrigger.LoadDisplays(toLoad, loadEvent, ...)
...
   for id in pairs(toLoad) do
     GenericTrigger.ScanWithFakeEvent(id);
   end
 
   if (eventsToRegister[loadEvent]) then
     WeakAuras.ScanEvents(loadEvent, ...);
   end
+  local loadUnit = ...
+  if loadUnit and unitEventsToRegister[loadUnit] and unitEventsToRegister[loadUnit][loadEvent] then
+    WeakAuras.ScanUnitEvents(loadEvent, ...);
```
Comment (mrbuds) [inline WeakAuras/GenericTrigger.lua]: UNIT_FLAGS, UNIT_ENTERED_VEHICLE, UNIT_EXITED_VEHICLE are used for loading auras

File: WeakAuras/GenericTrigger.lua [hunk 5]
```diff
@@ -1005,6 +1103,22 @@ function GenericTrigger.Add(data, region)
                 -- that are already in place. Replacing all those checks would be a pain in the ass.
                 trigger_events[index] = "COMBAT_LOG_EVENT_UNFILTERED_CUSTOM";
               end
+              -- custom events in the form of event:unit1:unit2:unitX are registered with RegisterUnitEvent
+              local trueEvent
+              for i in event:gmatch("[^:]+") do
```
Comment (mrbuds) [inline WeakAuras/GenericTrigger.lua]: support EVENT:unit1:unit2:unitX declaration for custom code

File: WeakAuras/GenericTrigger.lua [hunk 6]
```diff
@@ -1005,6 +1103,22 @@ function GenericTrigger.Add(data, region)
...
+                 if not trueEvent then
+                    trueEvent = string.upper(i)
+                 else
+                    local unit = string.lower(i)
+                    if WeakAuras.baseUnitId[unit] then
+                      trigger_unit_events[unit] = trigger_unit_events[unit] or {}
+                      tinsert(trigger_unit_events[unit], trueEvent)
+                      trigger_events[index] = nil
+                    else
+                      print(L["Unit %s is not a valid unit for RegisterUnitEvent"]:format(unit))
```
Comment (mrbuds) [inline WeakAuras/GenericTrigger.lua]: i guess we want to show a red message under the box instead of printing this in chat ?

File: WeakAuras/Prototypes.lua [hunk 7]
```diff
@@ -1126,20 +1126,35 @@ local function AddUnitChangeInternalEvents(unit, t)
...
+  end
+end
+
+local function AddUnitEventForUnit_events(unit, result, event)
+  if WeakAuras.baseUnitId[unit] then
+    result[unit] = result[unit] or {}
+    tinsert(result[unit], event)
+  end
+end
+
```
Comment (mrbuds) [inline WeakAuras/Prototypes.lua]: These 2 functions are helpers for populating "events" or "unit_events" depending if the unit provided is listed in WeakAuras.baseUnitId from Types.lua

File: WeakAuras/Prototypes.lua [hunk 8]
```diff
@@ -1126,20 +1126,35 @@ local function AddUnitChangeInternalEvents(unit, t)
...
-        "UNIT_FACTION"
-      };
-      AddUnitChangeEvents(trigger.unit, result);
-      if trigger.unitisunit then
-        AddUnitChangeEvents(trigger.unitisunit, result);
-      end
+      local result = {}
+      AddUnitEventForEvents(trigger.unit, result, "UNIT_LEVEL")
+      AddUnitEventForEvents(trigger.unit, result, "UNIT_FACTION")
+      AddUnitChangeEvents(trigger.unit, result)
```
Comment (mrbuds) [inline WeakAuras/Prototypes.lua]: I think there is an optimization to do on AddUnitChangeEvents, have to think more about it

File: WeakAuras/Prototypes.lua [hunk 9]
```diff
@@ -4569,12 +4613,16 @@ WeakAuras.event_prototypes = {
   ["Threat Situation"] = {
     type = "status",
     events = function(trigger)
-      local result = {
-        "UNIT_THREAT_SITUATION_UPDATE",
-      };
-      AddUnitChangeEvents(trigger.threatUnit, result);
+      local result = {};
+      AddUnitEventForEvents(trigger.threatUnit, result, "UNIT_THREAT_SITUATION_UPDATE")
```
Comment (mrbuds) [inline WeakAuras/Prototypes.lua]: I'm not 100% confident on that one

**Comment by mrbuds** [comment]
Show invalid unit in the trigger tab instead of chat
img

File: WeakAuras/GenericTrigger.lua (hunk 6 above)
Comment (mrbuds) [reply WeakAuras/GenericTrigger.lua]: done

**Comment by mrbuds** [comment]
added subevent validation
img

File: WeakAuras/Prototypes.lua [hunk 10]
```diff
@@ -1135,20 +1135,35 @@ local function AddUnitChangeInternalEvents(unit, t)
...
+  if WeakAuras.baseUnitId[unit] then
+    result[unit] = result[unit] or {}
+    tinsert(result[unit], event)
+  end
+end
+
 WeakAuras.event_prototypes = {
   ["Unit Characteristics"] = {
     type = "status",
     events = function(trigger)
```
Comment (InfusOnWoW) [inline WeakAuras/Prototypes.lua]: It might be good to instead of introducing a separate unit_events function, merge the unit_events function into events, but make it return two results, that is: 
1) The events
2) The unit events

Then, you can write a simple AddUnitEventForEvents(result, unit_result, unit, event) function which adds the event to the right place.

File: WeakAuras/Prototypes.lua (hunk 9 above)
Comment (InfusOnWoW) [reply WeakAuras/Prototypes.lua]: Can you test it?

Comment (InfusOnWoW) [reply WeakAuras/Prototypes.lua]: It might be that you really want AddUnitEventForEvents("player", result, "UNIT_THREAT_SITUATION_UPDATE") here

Comment (mrbuds) [reply WeakAuras/Prototypes.lua]: You are right and then
```Lua
    events = {},
    unit_events = {
      ["player"] = {"UNIT_THREAT_SITUATION_UPDATE"}
    },
```
is correct

File: WeakAuras/Prototypes.lua (hunk 10 above)
Comment (mrbuds) [reply WeakAuras/Prototypes.lua]: that would remove a lot of duplicate code indeed

Comment (mrbuds) [reply WeakAuras/Prototypes.lua]: before going further, would that structure work or you have something better in mind ?
```Lua
local function AddUnitEventForEvents(result, unit, event)
  if not WeakAuras.baseUnitId[unit] then
    if not result.events then
      result.events = {}
    end
    tinsert(result.events, event)
  else
    if not result.unit_events then
      result.unit_events = {}
    end
    if not result.unit_events[unit] then
      result.unit_events[unit] = {}
    end
    tinsert(result.unit_events[unit], event)
  end
end
```
