### PR TITLE
swallow stacksfunc errors

### LINKED ISSUE #1942: Erroring Custom Stack Information breaks WA Options.
## Describe the bug
If the Stacks Info custom box contains an error, it can break the WA Options. Oddly enough my attempt at creating an aura from scratch resulted in a _different_ effect of breakage. When using the reported aura, after a reload the WA Options are completely inoperable. With my aura, the options bug out* immediately on import and on reload, but are still operable, allowing you to still delete the aura.

\* The new "New Aura", "Imports" and such buttons don't show, a text showing "Creating Buttons 1/1" appears (with a fresh SV), and editing certain custom code blocks doesn't update the preview text in the options.

**Do you have an error log of what happened?**

```
161x [string "--[==[ Error in 'CS' ]==] return function()..."]:2: attempt to call field 'soulCount' (a nil value)
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras\GenericTrigger.lua"]:380: in function <WeakAuras\GenericTrigger.lua:376>
[string "@WeakAuras\GenericTrigger.lua"]:478: in function `ActivateEvent'
[string "@WeakAuras\GenericTrigger.lua"]:552: in function <WeakAuras\GenericTrigger.lua:512>
[string "@WeakAuras\GenericTrigger.lua"]:732: in function `ScanWithFakeEvent'
[string "@WeakAuras\GenericTrigger.lua"]:999: in function `LoadDisplays'
[string "@WeakAuras\WeakAuras-2.16.1.lua"]:2237: in function `LoadDisplays'
[string "@WeakAuras\WeakAuras-2.16.1.lua"]:2082: in function <WeakAuras\WeakAuras.lua:1968>
[string "@WeakAuras\WeakAuras-2.16.1.lua"]:2178: in function `ReloadAll'
[string "@WeakAuras\WeakAuras-2.16.1.lua"]:1824: in function `ScanAll'
[string "@WeakAuras\WeakAuras-2.16.1.lua"]:1769: in function `Resume'
[string "@WeakAuras\WeakAuras-2.16.1.lua"]:1589: in function <WeakAuras\WeakAuras.lua:1554>
```

### To Reproduce

1. Import aura linked below.
2. If using my aura, observe immediate WA Options bug by editing Custom Trigger Code, or closing and reopening the WA Options
3. Reload
4. Open WA Options and observe.

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Tested with only the 5-6 Official WA AddOns enabled (depending on version).

**Which version of WeakAuras are you using?**

Tested in 2.16.1 and the latest twitch alpha (2.16.1-12-g0636fea).

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**

Unknown

### Additional Info

The reported aura, reduced to a minimalist version: https://wago.io/3Ose4HxKB
My attempt to recreate the problem: [https://wago.io/mO7LaJiB_](https://wago.io/mO7LaJiB_)

### PR DESCRIPTION
**Pull request by emptyrivers**
somehow this particular function wasn't being called in protected mode
presumably just an oversight.

Fixes #1942

### CODE REVIEW

File: WeakAuras/GenericTrigger.lua [hunk 1]
```diff
@@ -3603,7 +3603,7 @@ function GenericTrigger.CreateFallbackState(data, triggernum, state)
   end
 
   if (event.stacksFunc) then
-    local ok, stacks = event.stacksFunc(firstTrigger);
+    local ok, stacks = xpcall(event.stacksFunc, geterrorhandler(), firstTrigger);
```
Comment (InfusOnWoW) [inline WeakAuras/GenericTrigger.lua]: That was broken in ceedae1f0de5a37968ccdd8729a07dfa3f5d692b by me, where I didn't add pcall to it, but to every other call. Somewhat suprisingly that this wasn't noticed, this broke the stacks function in that code path.
