### PR TITLE
fix

### LINKED ISSUE #4698: Dynamic Group Strata issue
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

It seems that cloned aura & normal auras does not follow the same rules for how strata is applied

This screenshot show the problem

image

image

chicken are cloned auras
rabbits are not cloned

### WeakAuras Version

dev

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Lua Error

```Text
no error
```

### Reproduction Steps

make a dynamic group with grow = grid going down, insert auras with auto-clone and auras without

### Last Good Version

_No response_

### Screenshots

_No response_

### Export String

```Text
!WA:2!nB53ZnX1vCCVJg3qxceqeCbAkOjtk1qBAWo2UuMonXRTKruHTzL8pG(dR7U7vAVWQDxU37Az7eO1kmbt4n9q(dqp3N0Fbm(VGZOP)f4N7lX)f0ZD3v2gOfk4KzYlRwD27EVNZNVFphjTfZkgDA6QzBK1jRZwxPnHBxI6xx6(OH2XkG7q5ge775WdcdpHHhBJniCNCvcc8KSq(AZvRMGkV(Z24Z1E2admaF90aFU4FpGkqxIVTBaF(aMV0AQ8ZwjVzNArEEtX42E0QMIqInDqoXwYc8ftykKeUu3QgZNjC1nWpK6TKCw96uU4CxKNE7x3XHAfvRwL1dP8RNV08fwOKHe)IjjItgTLiK65v0rOVJiYIUk1xwgxnBTURm1KLRSs5ktAwXic3CRqpY6uUPpPbvOBgVuRRtjEs39E155u8vnlpF(sLAh5NMc6DTd8IA4xwvbzS4ehwK4rVBRibTeRbt6As8y19HJ0IhijQYtRdUJM06QkvhJ2m5vn8ciofSKep8SgYSreswDdScShcUKUPThriu3ziyBqv30ZkvqMkWlGFJmzYmFMR8BhNt8znisQ7OrmNUlms4g35sr3Eo(OMcBCVZ0Xg3FkxHSpSKPvI262j5Z8o1PHNS89JiCAUcOaLBjxMK2HhNUQ3zBN1riXSRZdIctFRYygnOHiGln8d8rfssuOrRTG6vlwZhTYCZVltDU(eVfXvG72t7rIKOPyUWyrxFhB8QK4llG2GaUL5KtxCHYwy0AS66BNCuj(QFABHKgoPFDp6f6idSxnzhpJ2JD)qMZUtptUYsorsYXeIiA3ACuwtIKPDDoZzjMJ09O7MyklOEQQ0SkpLz(8Z2sTIy8C9P7MCQf9XdnJbwZnnMXS40MEkP9OPpnH)AAAiBd8DyjLtxMFTaEJyjxVDIOG3ob8Uf2MseQ8jU)6DGtbxRNd6xvpEfL7LlOQns0sTovMaxZObH5xaQeVAybyryj8ZJ9IrYAF3T(Oom8TlheXTPAWprdEh4i9SXovNGM(LBYcPv3U)xv6TlCumP0HJRdhthEVJFr4eFBhHBqZP8qXu4I7)7ddb)m4NdFa8lGZdNwhoNoCg4SWjHSWf0dpPQVDvALKoIBg4q)Nda)XNU79OOiPCWstvX5c)b4iyhRGivvlEW)YlpeCQEy7GYkRCu(oBD6WSs6AYveUemdxorW1cpBCW4ljyDfr6nW1AV3ZmQKF5kHN4aBW(IZojr7BjHJeEQ4iOlmqPn2XUcJjXVUBY5WwJMyv2SxIv52PzZ2Xp)UrcjR26ynf3AtROsGzNB28WP4ynPwtN4fAN0GI5q70cWxgE2cmojxzIVi3uOytrlMtodpeepha6FK9IJ1enClXjHTwk9MKmzvMGzHZrtR8doS1yUkvM7M927CJhvo3cvkvC287hv1b)XPf5Eip7b2S00yqlxkRURCt4xva(nQPqWLJV(RJVoC81jmugWWS4iWPs9zONaTa0QWNP3QV3ZfULoueUbuw1te7IrZCFR9YVuKJ9IrcF)(BLI8tZeeKboUGHoKpDuql)GC2kBmmOgoio0LKXSzSIcZKb(KU0RoHymRH)tJv5wCMVAmc110U)80mgBee0qRRdtO(9HIyvzn64JD1X)DGPo8WQB9rWT1WskTjdUtv4p3VB6yXnujDtWF513eb)14Eg4V5MYJxOvF5xFZpSsAhfuDRtdenWcJzdoan2)d1WuSo4cSnH7Qb3d)Mh0axTpeeBoHq4(axdeGeIQcRcnHVCqyJpg(cnynyD4bXQ(WVKQN4dMaEOIPpSQInpb(g4XXie20f2sdr9SMlzWnhzuZr47jpD6lp5gf(7vJndpAtL(91UWxLb1mLf5Fep3iH1dQ98SgpTdbIFZTC)aGyfztymc7h8QBSqeJ8bPHckiAqgTpLpGTFFU(Pk7jklk0Ie(t6E1Ito8VFmF7MrefLrPrPvOKDGFe41Y6QVjSwLUhcSPL5)xS9QCMyT)w3wHW5w6pxBnkcXE6BENXIUFPn4tU4NUh73og8o5u)durF5jvbq9kXCJYfQlp5mN)7UdkLj8oDPFV4VpKm)7NPbiZpi0shl0FEWyfxCzrPGrMF2f)V4Bhtz)qCHKwbUeQHu8Z0thj82QMVQz2h8Fa9JcG)goB4W8JPPtuM5)9OKX77qrDfLLVs97N(3O4vUP4QfwCKzuceQz7pq5HvZU6)A5)Z
```

### PR DESCRIPTION
**Pull request by mrbuds**
fixes #4698

### CODE REVIEW

File: WeakAuras/RegionTypes/DynamicGroup.lua [hunk 1]
```diff
@@ -1518,6 +1517,14 @@ local function modify(parent, region, data)
       end
     end
 
+    local baseLevel = 1
+    for child in pairs(handledRegionData) do
+      baseLevel = math.max(baseLevel, Private.GetBackgroundLevel(child.region))
+    end
+    for child in pairs(handledRegionData) do
+      Private.ApplyFrameLevel(child.region, baseLevel)
+    end
```
Comment (InfusOnWoW) [inline WeakAuras/RegionTypes/DynamicGroup.lua:1526]: Since the frame levels are don't depend on the sorting etc, you can assign the frame levels again in modify.

I don't like the GetBackgroundLevel function, I don't think it works and I don't like the hardcoding of the subbackground subregion type.

Also you want to call SetFrameLevel not ApplyFrameLevel, I actually think the easiest is to adjust FixGroupChildrenOrderForGroup to take an offset parameter, which would be 0 when called from dynamic groups.

Comment (mrbuds) [reply WeakAuras/RegionTypes/DynamicGroup.lua]: The complexity of the change went down considerably

File: WeakAuras/WeakAuras.lua [hunk 2]
```diff
@@ -4055,7 +4055,9 @@ function Private.FixGroupChildrenOrderForGroup(data)
   if data.parent == nil then
     for child in Private.TraverseAll(data) do
       SetFrameLevel(child.id, frameLevel);
-      frameLevel = frameLevel + 4;
+      if data.regionType ~= "dynamicgroup" then
```
Comment (InfusOnWoW) [inline WeakAuras/WeakAuras.lua:4058]: Instead of checking for each child, either check once before iterating or make the offset a parameter of the function and call it with the correct offset from Group/DynamicGroup

Comment (mrbuds) [reply WeakAuras/WeakAuras.lua]: done

**Review by InfusOnWoW — APPROVED** [review]

File: WeakAuras/WeakAuras.lua [hunk 3]
```diff
@@ -4052,10 +4052,11 @@ end
 
 function Private.FixGroupChildrenOrderForGroup(data)
   local frameLevel = 1;
+  local offset = data.regionType == "dynamicgroup" and 0 or 4
```
Comment (InfusOnWoW) [inline WeakAuras/WeakAuras.lua:4055]: Tweak this a bit more.
