### PR TITLE
Bugs

### LINKED ISSUE #1579: Improve OPTIONS event error handling
While testing on 8.2.5 PTR with a old SV i get this error from an outdated aura, and it doesn't tell from which aura the error is coming from

```
2x WeakAuras\AuraEnvironment.lua:47: Usage: local className, classFilename, classID = UnitClass(unit)
WeakAuras\AuraEnvironment.lua:47: in function <WeakAuras\AuraEnvironment.lua:46>
(tail call): ?
[C]: in function `xpcall'
WeakAuras\WeakAuras-@project-version@.lua:5616: in function `RunCustomTextFunc'
WeakAuras\SubRegionTypes\SubText.lua:221: in function `Update'
WeakAuras\WeakAuras-@project-version@.lua:5392: in function <WeakAuras\WeakAuras.lua:5387>
WeakAuras\WeakAuras-@project-version@.lua:5477: in function <WeakAuras\WeakAuras.lua:5444>
WeakAuras\WeakAuras-@project-version@.lua:5561: in function `UpdatedTriggerState'
WeakAuras\WeakAuras-@project-version@.lua:5328: in function `UpdateFakeStatesFor'
WeakAuras\WeakAuras-@project-version@.lua:5301: in function `FakeStatesFor'
...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:1788: in function `PriorityShow'
...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:1660: in function `PriorityShow'
WeakAurasOptions\WeakAurasOptions-@project-version@.lua:1615: in function <WeakAurasOptions\WeakAurasOptions.lua:1580>
```

I think it was coming from this aura
```
!vNXwZPnp2)lzMDMUZ2MX2Cnp0hacPjziq2ysZUtBniBla9fJfFw2Kq6u(T)Dosw2YCjjDFyNDhAaz5ZDDUQ6z7n2ZLaFL65k8CpNU2ZDPNBi(p8njbdOXZtx4nSwtlpxFEsinPlj4XWe(kp3UrSxEHKeUD6yopkLbBrYsxWtgTkLXJfkcVz0SzcAQ3Wpz3aiY8ew44nROEU3D1xUC85JEyOMY94r8eaPH2EdT8g6i)UM8764MOuUIeqXx5sc08WvKsssvmBglMjwOwdlv7cRttyZNttekQpUyd5sP0qYsiEUzX010yeb2skAhGDr(45A75M)QlPKiWM4kY8L7CBcDg7zpx3B7pyakI0OORcZ1E)SzZCxWFAeqcH83oGGVgyymzjnhOmusDxfr2asubDDbur6oPxh3XtCh35oqydPifvgWl7p42lUFGIcLkKuHdzI)iloNvKOiLbBnDScSB4Hu8eXcHnGhLTm2vzATrdxknjMe9vWGH6(qhytbnA2TCgAaKhCivzZbTQx)HJ7FN8uqkaWXLBeNi9GsjrGI4GlxMbEifhhY93B7GiIqS3UGbnyVnZe0jkW99Ct4r09GibvND3C16vhH3HmWAha7SzVxnt5RT3(S45j8Sv7lWSx2JZORqEGJPBUT0n3w6MBlDZToTbcmjMTKKsrTteasS8GjGhpJnp3XsgYGVxTQF4C4K2E70BzptHJ7e6CqMvokHBaNnwGsAZH3ffsmqsWHGh3yEmfTzHSmbSTfEiYwcULdBGctaevNF6RpVbHboYJtVaSoG(4ExNZV6Ex5jZajMfIMobGDt8O6PshTuEWATpwBlhlGvmiO7ocdYPea5uc5pbH45K5QyjvYZH8aletmviDxKaXtk11T3D97dzvMHBbr6KuIKDziXFH4VY)67TV)8lqcXFYZDq)lgJswQkuh5WZfjTCWKwGUgYmYPPLnVU6tQC)dDQO8KkkRQojYe1McksobsNLew87h6IKBVp4vHufz8Mhb6QV6xDA96aazIu(YX0NrgiZyWJ)WFF71BNQ(WMTDkMBCcnE9PG6Ls3onDbnUec1NeAAws82Pp0zspmUu6Lpeoa(qvSpfZ7zqFAC42RLFv9JrHdRJ6bQofCFIbAExtD5(vHy0JoLTgszqcydyGncr41klKNh3ZTMDBmbiMXH4drl(YKNa2ZPX0ewWHtVFKQdvt1xwEPDodrlMSsmh3F70oYYsXYDX1BNEdraPN3O12jlyG0ORxHczjD81Ekkql)T4GwEKi(42PtY)tl2gBHm34XD)tzNoFhxMyEQPFdyAMGvqG9GJAjj)8NFGsEe1jXPlpItvPBvAsgDhNMcGQWyTcSD6N)82PNin75vqVVxV(UUNGqEyMfXHuTAnkEghOHPsGBl(wU((J9rxY(sCpmp0FuwEn1ovgw8djd)5XrQazWEkHfnlF8THhjUeE1z5BcFWcs8CA4VdlGo)4xcUI)o4SkHppHkeyABjENiDJp5DGAHtUeVVqtD1g(pODiFhurh)jjsXr33S)X7ax6ZRykShZkfdCnK(C6)43MEyoPkkdMhllH(7OpyU9D0fNFSFCYUF(1(VQsewLhQgrcVQituEbi0Xolp)Br(iirA39BVo)PE8L(eiIDaF(rB)vf8MJc0tqVr30TZ4jdg9Lj9)kuqyY9dV4QbqDH(NRfivU0dvutRdfX2YaeLYuT)DubK5SXYllObpwi0hQt8IM6X2nUdA7Ed0J42P9G01PAP6RKegXpcaZ9NgNyN4d1OGCt)6GTZFGM3TvTGEGw1FKsx1b7Ao9o0)u2dzz376QNhO5lrkl4XnNRlkL3SWR3VQASSm)7K9BAujf8ENiwqGYU)lJc55(iz(PYooKqPw(3cYFm4T5NeUzCuD6)8kmfYdKnv457ywsdO)3MsOC7s7vN7hpkF31mbdo5KDoGpxPRKr3dM1jDhnE8OB0nSShDrzw5YaGp4QH9n2x1rUDDnYMMnzZPuvxAdhbOLI60)rMzJ2m()eZT)Xn3JhD7)nS1WQfu28f44qgJ3ESbaXKgyMo54zhzEZdov7Hha(vgnf50l4ya(hFy7Jn(6bNA(4diFW5P3Dux3zr0N1XiZGjl3SKO60MQ(5jG0BMHDix8eUAfm2eUqp1YB7tIzMUiH(Nz04Gn4yZonmgBZsEdiyB2xfitlwRvJATuyP8j8Zst5XJGdPi0xw(Ifq6VyW7woy0bUkleitpfZ5XnN3woEHeAtNss0QfQbr)F4rgHYAcsk(EAXWImWMa1io4DUvmsbErczy9ZRWssGph97Dcdhfl(ErB(F)gAiJ8DxeoX37YEKEjpj(u(COQFiFsoL8LpOiMFvDOcqAgNpUy5f(zaw3sW(0N0T1cTUWZBFr2Y(gE22PprWrgWxO6Tg2mz7uyKrJlIy71hAGMpxmCY1ip2ov1tplu3nFrxMFuxU)xMusovXUn()TZAvVPtbfSTaCNrIeGi)lyPuz4lHyRqzdgG4KLAGT9znBz3Ua927JDijr6QBGKCo3k4OSrAuiYXpxQg)0aphqsB3QQSwft6A0UhXelnrRzdhRsvSXEyTGhTboy44fmlirRvDQxsGMonn0XdzI8jjjmAIjo1BxVwboT2JNHS1G3oW7nlRWQ6NzvAAAUhAInl95WKJ8zOyVIAQMwTQD2zf4w7aIjucIkstWrpHjIsPbQrssHLMgmBR2oTTEn78ckjs6pKkheBxcCwBlR2v0IDeerufNi76wnm8b3)eIicGwMrX3aTw1lLXMNUpsGIg)NzSiwQPtuTATpZ(vTsPjuAfPRrnBRx5mjHUMTgSPgO0WPDZQ6Zo8ynzjmuhlaCzx6Jf8o0Tmifgc0IUzWtZwN1Ou8RqzdLSXBdJJvDRwN9MG1WUIx1rGQPJTt93ekBBiq6TjMD7go1FBfOrthhNJb1VkUEpzXMx4qQ58A360SyJxNZe4isybaSomxEBBqQt3IRcxFpXqMZEf5NNcTdb7)u(vdBT)vaF07k2K79JvmVB(vgV5pQ19f6)mO5CzrgCQPIIJ3cLbXEZOQMgabOCKj)DU4y1GrQPinURruUwNpuy(10cphLPNXtv1QKaQ3HnnLaPAW(MuiLw29u5TtJVPR()Qa5BxJ996Gu27Vo
```

with
```Lua
function()
    if aura_env.state then
       return WA_ClassColorName(aura_env.state.name)
    end
end
```

### PR DESCRIPTION
**Pull request by emptyrivers**
# Description

Closes #1579 
Also, improve readability slightly, as a short-ish term improvement for #1208
## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: WeakAuras/AuraEnvironment.lua [hunk 1]
```diff
@@ -44,9 +44,17 @@ end
...
-  return RAID_CLASS_COLORS[class]:WrapTextInColorCode(UnitName(unit))
+  if unit and UnitExists(unit) then
+    local name = UnitName(unit)
+    local _, class = UnitClass(unit)
+    if not class then
+      return name
+    else
+      local classData = RAID_CLASS_COLORS[class]
+      local coloredName = ("c|%s%s|r"):format(classData.colorStr, name)
+      return name
```
Comment (emptyrivers) [inline WeakAuras/AuraEnvironment.lua]: oh, oops.
