### PR TITLE
Bugs

### LINKED ISSUE #1185: Optimizing WeakAuras.NewDisplayButton
It calls ScanForloads. Why does it do that?
ScanForLoads is hilariously expensive.

The update thread used in Transmission.lua calls this for each installed aura. This is possibly the reason that the whole thing is so damn slow sometimes.

### LINKED ISSUE #1219: Dynamic group horizontal alignment
**Describe the bug**
Dynamic group require migration for fixing alignment

prev
top group = not aligned
bottom group = aligned after changing alignment to top, and back to center after that

[weakauras-140126336#2-20190301212229.zip](https://github.com/WeakAuras/WeakAuras2/files/2921559/weakauras-140126336.2-20190301212229.zip)

### PR DESCRIPTION
**Pull request by emptyrivers**
# Description

Fixes #1219

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Smoke test!

### CODE REVIEW

**Comment by mrbuds** [comment]
Do you have a profile before/after the changes like you did for #1185 ?

File: WeakAurasOptions/WeakAurasOptions.lua [hunk 1]
```diff
@@ -3905,7 +3904,6 @@ function WeakAuras.NewDisplayButton(data)
   frame.buttonsScroll:AddChild(displayButtons[id]);
   WeakAuras.AddOption(id, data);
   WeakAuras.SetIconNames(data);
-  WeakAuras.SortDisplayButtons();
```
Comment (InfusOnWoW) [inline WeakAurasOptions/WeakAurasOptions.lua]: You need to look at all callers of NewDisplayButton to figure out whether any of them relied on those calls and test most of them.

E.g. OnDuplicateClick -> DuplicateAura -> NewDisplayButton seems to me like it should need a ScanForLoads for the new button + SortDisplayButtons (?)

NewAura might need those calls too.

Comment (emptyrivers) [reply WeakAurasOptions/WeakAurasOptions.lua]: It seems that SortDisplayButtons isn't actually necessary in most cases. But ScanForLoads certainly is when creating an aura while options is open.

In any case, I think that I'll retract this change for now and do some more research. I'd like to get the other fix in sooner rather than later.

**Comment by emptyrivers** [comment]
@mrbuds here is a quick report I generated by tracking how long each thread that the dynframe executes runs for: 
```
Without changes:

Opening WeakAurasOptions (2 threads)
stats for thread: LayoutDisplayButtons1 
total frames used: 201 
total time used: 470.11430323124 
average time used per frame: 0.85026608236987 
most time used in one frame: 4.7096840143204 
least time used in one frame: 0.050075769424438 

stats for thread: LayoutDisplayButtons2 
total frames used: 638 
total time used: 1324.8011082411 
average time used per frame: 0.92656005755487 
most time used in one frame: 50.8285125494 
least time used in one frame: 0.60091018676758

Updating https://wago.io/bfaraid2/2.0.9 to https://wago.io/bfaraid2/, selecting all options:

stats for thread: import 
total frames used: 286 
total time used: 18389.984524965 
average time used per frame: 40.278869158738 
most time used in one frame: 656.6710858345 
least time used in one frame: 0.3880877494812


With changes:

Opening WeakAurasOptions (2 threads)

stats for thread: LayoutDisplayButtons1 
total frames used: 201 
total time used: 466.03848743439 
average time used per frame: 0.8728787691439 
most time used in one frame: 5.3841749429703 
least time used in one frame: 0.041133761405945 

stats for thread: LayoutDisplayButtons2 
total frames used: 639 
total time used: 1168.2553397417 
average time used per frame: 0.899969361944 
most time used in one frame: 50.069965600967 
least time used in one frame: 0.60934114456177 

Updating https://wago.io/bfaraid2/2.0.9 to https://wago.io/bfaraid2/, selecting all options:

stats for thread: import 
total frames used: 286 
total time used: 4544.7094234228 
average time used per frame: 9.7077901129956 
most time used in one frame: 599.92647027969 
least time used in one frame: 0.40750503540039

```

I would estimate from this profile (as well as anectodal experience) that this is worth pursuing :)

But that will need more time to mature, as @InfusOnWoW pointed out.

**Comment by emptyrivers** [comment]
@mrbuds if you wish to verify my results, then you can apply this change to add a profile to the dynframe:
```diff
diff --git a/WeakAuras/WeakAuras.lua b/WeakAuras/WeakAuras.lua
index 8d94e79..27a5f6e 100644
--- a/WeakAuras/WeakAuras.lua
+++ b/WeakAuras/WeakAuras.lua
@@ -4352,9 +4352,13 @@ end
 local dynFrame = {};
 do
   -- Internal data
+  dynFrame.debug = true
   dynFrame.frame = CreateFrame("frame");
   dynFrame.update = {};
   dynFrame.size = 0;
+  if dynFrame.debug then
+    dynFrame.stats = {};
+  end
 
   -- Add an action to be resumed via OnUpdate
   function dynFrame.AddAction(self, name, func)
@@ -4366,6 +4370,15 @@ do
       dynFrame.update[name] = func;
       dynFrame.size = dynFrame.size + 1
       dynFrame.frame:Show();
+      if dynFrame.debug then
+        print(name,'added to thread list')
+        local actionStats = {}
+        dynFrame.stats[name] = actionStats
+        actionStats.start = debugprofilestop()
+        actionStats.count = 0
+        actionStats.records = {}
+        actionStats.finish = debugprofilestop()
+      end
     end
   end
 
@@ -4373,6 +4386,29 @@ do
   function dynFrame.RemoveAction(self, name)
     if dynFrame.update[name] then
       dynFrame.update[name] = nil;
+      if dynFrame.debug then
+        local actionStats = dynFrame.stats[name]
+        actionStats.finish = debugprofilestop()
+        print(name,'removed from thread list')
+        print('stats for thread:',name)
+        print('total frames used:',actionStats.count)
+        print('total time used:', actionStats.finish - actionStats.start)
+        local ma, mi, av = 0, math.huge, 0
+        for _, record in pairs(actionStats.records) do
+          local d = record.elapsed
+          av = av + d
+          if ma < d then
+            ma = d
+          end
+          if mi > d then
+            mi = d
+          end
+        end
+        av = av / actionStats.count
+        print('average time used per frame:', av)
+        print('most time used in one frame:', ma)
+        print('least time used in one frame:', mi)
+      end
       dynFrame.size = dynFrame.size - 1
       if dynFrame.size == 0 then
         dynFrame.frame:Hide();
@@ -4399,7 +4435,19 @@ do
 
         -- Resume or remove
         if coroutine.status(func) ~= "dead" then
+          local record
+          if dynFrame.debug then
+            dynFrame.stats[name].count = dynFrame.stats[name].count + 1
+            record = {
+              start = debugprofilestop()
+            }
+          end
           local ok, msg = coroutine.resume(func)
+          if dynFrame.debug then
+            record.finish = debugprofilestop()
+            record.elapsed = record.finish - record.start
+            tinsert(dynFrame.stats[name].records, record)
+          end
           if not ok then
             geterrorhandler()(msg .. '\n' .. debugstack(func))
           end
```

File: WeakAurasOptions/WeakAurasOptions.lua (hunk 1 above)
Comment (InfusOnWoW) [reply WeakAurasOptions/WeakAurasOptions.lua]: Right, it looked easy enough, there aren't that many callers and looking through them most call both or at least one already anyway.

SortDisplayButtons is used to sort top level buttons, since those are sorted by name and to filter the buttons according to the search.

So, make sure to test that, e.g. for Duplicate button, with top-level auras "A 1", "A 2" exsisting, duplicating the first one will create a "A 3" which should end up at the end. With a filter for "1", and duplicate, the new aura should be invisible.
