### PR TITLE
fix nil error in Action Usable spellInRange condition #1697

### LINKED ISSUE #1697: WA bugs when i wanna edit in options. screen gets blank
**When i click on my WA to get into "group/display etc" half the times it bugs, and the screen gets blank, i then need to /reload for resetting my WA option for not getting the error again**
 To load the page?

**Do you have an error log of what happened?**
This is with only WA + bugsack + buggrapper on.
WA bug

https://pastebin.com/KfYHzywk

 

**To Reproduce**
 

**Screenshots**

i added a screenshot of how it looks when the bug happens. The bug only happens when i work with WA options to change the settings. 

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes, the last pastebin, i only have WA + bugsack + buggrapper on.

**Which version of WeakAuras are you using?**
Weakaura-2.14.6 (newest updated on twitch app)

**Was it working in a previous version? If yes, which was the last good one?**
I never had this problem before. I just copied some old WA that worked the last ½ year, and changed some spell ID to work on a new toon, and suddenly this problem arrived yesterday night

**Additional context**

It just not 1 aura, it can happen to all in the same group
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/3613514/WeakAuras.zip)

<!-- In case you do know which aura is problematic, please export the string and paste it below. 

!TZvAZPnVw4)lDM7mTZTTdMLe67D6DgilTP3eiVysFB7ha8Ic4gJn1lzPFGF73ZrYglzlBmekK0YmDAaBz5Jo6S8CEKedug0FGQ)a1QVvP(BpyG60bQM4)GRo2Z9UbQFSBVZ(w3o9BD(avDxptIxBnJBm9CNnqTTT1p)PMN58r9DDTdSGlDF3RV2NemOtLbQpe)53u9DWx1CmM46DPRLtWa1JoPt)t6f3Lh5A76bVZok4d2Pk9)Rr))64fHhaeg1zAge8RQAgbwUo(uzpqZla(a0KRTCS8NW(m8r2vHph4znEmXZN9c6V4c4hnj6HxFD)hMrGH6jNF5PxbJZa6x1c90QcVGzeB7Zm9z9RFOo5wItGk8uw3pqD4rTu7puTFREqNfIVu1z2ApaDUQJ2us0trFe4fq0SdMK0jx6rODI6LNC(5y7cDseTaMWB4Aho1jzO7PzAf6d6OkuvQ1unuvWRjunbbhV4q24WNy46aYF0WYX1HGD8unlNY36f62Y1E4j0STg7KmrdshDGHggW4VhzC0mi0uBxnQfxOpzOHTMp2BEHeQU3aVX0qW6kE6K1cCaB5m2gA1L9o7e10TY36NK0pkCz9iJxElofQfNc1ItHAXv5TnOdbQ6LmOn0DgA2SjaMf7a94pDI5yqguMp6sR7j2WeeDKXSOmFamcSmapPWzXTxffSoOHLlmDXuyWSSZ1wJzAdp3a2CkQQg7zzY6REhtBgOhDcofCaaXxTxRJp7kvuprnpom(De74vh0TwtbJYonavQRXTGxaTNBwHA)yzIgFZhbsVUM38r2wOWeIx(VNC6hU6LD(C7U4SVhyldZjAbAm)pQR8P4vzcN6r9o5KoO1G91s9WpZHkqkSr0)yzc(bOqP5zCoXzm(TAhGw0Hbqp3DwqI1bAFzX9DWk5C6GshDZdiEoA2FoEGvTg9rw4Qp2gcIPZhlQrorImGqyMU35OEN1m6uUrOFG70(K7dUAMjAgOgg934MsN61Lgos10Dy07MpAeFmk2qbBeZyuN(94iPTzY(x4INk3BNZVlpFtoV9Y16eV9s1E0DlWY4MhooQf4yjzGLNxMsua1KybrHNbv(q)jAMId)O3AOoE)OwX(4)Yp6Rgl)9rB31U4m)PEw)C(O)ouZenSHKyIV7sKuIR1FLxsPxoXvO1v97gD1BT8T0TPwn0VlykEwNoN0By7U9739IEN9Hp2p2uLVZPHhi9Pd8oD7Cc3qIfArPA8J9L0Ye2iMdB3R6F(zWdtN8MqSgpbAwn5rjWzYZHidqwNMSVDQh5hHehJhWqLvBigbFgjqxliGniPbRHrP5WOy5OwdcL6eWfbVJsJKa1DuEhy8h7Em8wYeldU(APb(Xhk6nOZNsPTq)DLv8DDGuXuNV4KnXcvnjDmTnTZn7IKWFO6IPYBDK6eA8v6LaP4gqL6tdsllmMauQBiKzTWxEqp0bdfx(8mwGNyuC7Fe8TwT)U3HQJpwA0u8LZBov6q7LW3koUiACESLVgyOBsJpgg4IATF66oL(sbv5hweEiksN6ImS4W4ZUwaSYt8cPYoItZxlaJUWc4ApBctCVJLjbTCPMPr5suQiMt1YbnQPplvx1UyuHG6W4Mi5MIdKdlhIxuDI7DDbPYN(3wq4)BjmdKXehINLrudWHMWfOprl770EWpnCrQ5fC3XgMX2Qbr5c0fatghggaDG9re2sMScpvhOLl6aCCymrZJLNIcLLE)ovR2S6bSzIHu5O9IaSq4LqF2DyOJpI6)OVeWVsrslhPBmE4JISxaStEUJ9aVH5JEPkkKVI9(j3dPwhMi2TrZEnBv5JdH2jcBhn4qqyqgIWKadA6agm9lCnz57DNQd(NxOfymb010PQZDVJ4hWPmXgoL1cPgbPaXxW0pgWa8Isz4jofio5kmXhDNwuOhZhDf1BtC(uuvLXLkRkROP3CMjZAdlQuZAYjPmhimsrQHcLRzWmK3q3zeq3GqI)VVxMyePTUeBSOssCaq7n6BVJsTmtaZyp(bvYxDG5)OTQn3xODyBXjqzQH6svdX1Hw(kpLAGEHLpMzRKfJkrhcoQDDSFiEKfRafSk5JvIHNrBURD9MYgU5fQswOdj6hvtl)Vh6efTvZ5bgY7Bj9znJkOXzI4QzGfEh0iG7lNcgLVB18SyooUoXrJWRAhUONMO5mMK0nS7bc9mp0Ol4bHCtbCU1zFHVPk)BSBVO2KnfuhHgYcL50dfKfcxLfeeSIcit4yTIlB(PnvEx9dB2OAL61uQvRE1bx)MghGUMN2OsZdQR0SELQhC4HvpSs0DIZ6N8Eyqec48PxMoOvNJZxjuJVLr(EiTtOlot(vPXteJII4P40DtqsS4MqlRoJw8wqclmr2grGvAhtcq8BpUoZ0Gq(Lw35kdLjBAqPzTlkbxHaA4JRwiCMsh0P4OERmAhHWKlfVtQiwRiYVToiNuavfcmxAWnjDWVsOm5MHERHNr0uih7rbv4obkJmmFsqXKJ8xmCgrWklbixgWmrbKFxLsbLH3vvukkgSISXFmYLsOa4XSSmKQfn1ueUgbuABEOms5gqcFapLxlG9SdUTyhmhA(KWAybueUGhXne7GIK3Sj5kSAfW1TtvLDdJHcmcUe2dZHXWsrpyMfcyzR3qEReAj8aYsRippAIlqbh5BjmYLEnn4PXCbbGXmcMhJHRkbHaKQJBnF0)E(iv3lE1JGLtkhQUTVPk5W6ivQcuhkHovjm(UV2ZFtR9mPMZ4Yq351EwBNx7zXlHPeCks8y2dpyxdpOulHygmezGhKBQDH0MsZPVbsE3EzjVLbWydKdphqrlbgusMF9WGaxNUqFafNil))tzO9PXMWNUplwIhbYLeqisHDiTmjrSPlqFSS1PmlAdvQB68rh5Pbsx(WhsJZinoKseJHIaPT(N0R89lAp9h9xgcK1DDm5PZOsJAnBKQy7ncpFpQIUZYpxkg(KsEj3qmf)Gpvz3ls7VYlHzH00wAc)k1Mr8jh5FPCi3MC)XMU2V(upVRryjaRR)8zrDkoUEdL9X13DX1BOSpU(Afx)FaFX)A(iKLNTE09gkpYO7fVnE3xa8JUa42)QlaUAL1Ra4n8UNndBZCLhxMTRQqPWXv5w(6QfkEoNIFFQxB66T3BLuNvXeJlwBFPigVeUBBq(YLgyDTPjFDQJhBadgucGi02heZ5JyA35JE)8riEMHeNBFB01(08pX(0BHxfGg9VoYMO51Y2M637)YxL((QKa6TE5lyXxFXRt1LV(f97E5lEDLxx5v)NiRDuBC3KP6H9)I2NpsvOO7LSrSxDS8mKo(lyuoIq53)(9a63kK(hPSZvz8gHzllheZLwGqDxP49VWP3QCtVB(LaOXoRsLFrh7P9RzWFuh4Oh)2byBS0bB6tkuzxZG0fpScRAWspurIywKqw)t4ZBinH9rkF4JF92)339CBxk4uRnChrm85bcldAT8qHDTfXXmNtXK8da7VIdYurNUKcijQGTUBb8fLIzPm7TWIokaYOiQawDwT94BHujiNwTA1RxR2MKPOOoChruKmAWEAqtKWmPuIII8KwrcIw((gnp6HyZu75()3AU)pGhrTK4X7wq15Tc5PbvN7cIV8FsbEAWEt2TlXE09p7q3lICAvq9Yxg7kG6vs1JILxkJhVsCY2tGG9CMT20iGLcbnBP1pIDoZXAE3et349Rd27fB0qShsa8FJaw4n9jGBLpk)5SYP6fDq(LaeEDpn)hazfpyZI9nFe2YotoBI1lnEqSsNYT)KxSuEFRT5AKYMOECOG3VX5F(bm(qEGXLiR5ZYd)CwhZcI7NkAE(H9tNGitYLn0bDUzLdvuY1JEvpXZIHjYpJWgmjq0ayBCuN3v)oUSziaHf8VLVbXXFDo)ZRpjirZrBNJ1QK8e7lm83Zts6Avyv5Rpk)f3zdSEo5xgRWw)r(s5uWUtrS21Nx)cqMZVqDXhTY2F3llRvL(KviDDs2y)8ZLj4APkC(EHt6H0fTjnZgR9AOVhS8t1nCIsMrwC(8vuRx(9asZDjJ15Dsqlfb07tV)75jbD9499(1BNoS09pu2mrpNXAqZIY(jE94V(T39LsvlE5tSUUzKYca4XSrjSSbddsoBL20zJl5p9RpLHpT2h3NLvK3QqJDj2Bh67Y92b34(XrLbx1SknQ38WnjfgrD4kVBo(tKeJfU5BnYlyZo73bh)otunUvTHhVEvShg8)d

### PR DESCRIPTION
**Pull request by mrbuds**
This check was done for "Cooldown Progress (Spell)" trigger but not for "Action Usable"
Fixes #1697

### CODE REVIEW

File: WeakAuras/Prototypes.lua [hunk 1]
```diff
@@ -3941,7 +3941,7 @@ WeakAuras.event_prototypes = {
         test = "true",
         conditionType = "bool",
         conditionTest = function(state, needle)
-          return state and state.show and (UnitExists('target') and WeakAuras.IsSpellInRange(state.spellName, 'target') == needle)
+          return state and state.show and (UnitExists('target') and state.spellname and WeakAuras.IsSpellInRange(state.spellName, 'target') == needle)
```
Comment (manung) [inline WeakAuras/Prototypes.lua]: there is a typo here that is causing the spellInRange condition to be broken. state.spellName vs state.spellname
