### PR TITLE
ensure we always compute the correct rect for a dynamic group

### LINKED ISSUE #5023: Transitive anchors are incorrect when root frame is anchored to PRD while loading for a specific spec
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Apologies for the confusing title, I'll try to explain as best I can.

I have a handful of dynamic groups which are anchored to a central dynamic group, which is itself anchored to the Personal Resource Display. Upon logging in or loading into a new zone, the central dynamic group appears in the correct position, but the other groups are positioned as if the central dynamic group had a width and height of 0. Opening the WeakAuras configuration (`/wa`) recalculates the positions of all the frames and resolves the issue until the next loading screen.

On login, the left and right dynamic groups are positioned in the "center", respecting their own configured offsets:
Screenshot 2024-04-19 110917

Opening the WeakAuras configuration resolves the issue:
Screenshot 2024-04-19 111436

From Discord, @emptyrivers suggested I open a bug report.

While trying to build a minimal repro, I discovered that the issue does not occur if I don't select a specialization-based Load filter, and I can work around the issue by loading based on an ability that only my spec currently has access to (for example, Keg Smash for Brewmaster).

### WeakAuras Version

WeakAuras 5.12.8

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Lua Error

_No response_

### Reproduction Steps

1. Create a Dynamic Group anchored to the PRD, containing some frames
2. Create another Dynamic Group anchored to the first Dynamic Group, containing more frames
3. Set all frames to load for the current spec
4. Load into a new zone

### Last Good Version

_No response_

### Screenshots

The provided repro is configured to only load for Brewmaster.

Upon loading into a new zone:
Screenshot 2024-04-19 175259

After opening the WeakAuras configuration:
Screenshot 2024-04-19 175334

Removing the Brewmaster spec from the Load conditions makes everything load properly. I can work around the issue using an ability-based Load condition (like Keg Smash), but that causes issues with some specific auras.

### Export String

```Text
!WA:2!TNv(3TXv1)OoXTeLsITBIBIPTwnTnnP0gsKxYsBPOXsYXjk2UJuItkqTgnZtAM4rZmEMrEdkqmHuxOSuxOS9Ln1wwdqrhkBh6bQp9hOS99IBb6YHsXCi)g)s(lG79nJKLsIDdP9WpLFrAMNEVzEV7NL799uOJ0QBUU3XUIUJ90AXwvBvD2ilKtwzuvhl7ETmSCoGGGWqc7ChDB3QILPNJLHbtTxnDdvhM5(MpdZ1lsFowLSJ0z93eT(B21I5SCuzoIbpy7Mfn0NEAzh1izSSm80Tl7zPmoZXv3YCtHEqZfKl5Pz5mOTh2GB45Kn1lktx3JKRNSJxY5zYUS0E4uOGN2vj6nLnt00YKTGAjhEhhHAYXLHZzv3zOENbBawVyrzDZKWB)QG1bRhAgAbAfwFU86M6UANxZ(ZAnNPgmFExM3Zx2HvaF20tsQaTYk73J06tZAsYvr2GjuXVj)yxOqHec6tc1cm7wspwjzhwKKLmmImSMUhRISPcUshYs30lxVjgitcjhzf(YUh4QddBiSio38cpJNJEHc4kQ9T6eC5PkRYYvkFEA64S)ePgk5HtbRtsgJarNX1Mzy0VQB4fDlLJnoZ0ln2v9jRmsVXsNzK0zIjLrSe(KZzBipfZrYuUiZnSeVR52pt2WtR2qhYHHdvk9qjsLAUsMbV)Wot6hxcnV)s0)U1y3I)AkPd(ihcxUMEAZ5YmYZxKqhBrxvKihNfVJ5ykBCeFG)rLKnS1KfoBDdNwBrhskUOHLSAYCEye20RnPILqstyrCrQ0gC3HLumKDDPReDrOGUiag63eNrcvYtplKUi7jlugxvsCC0nC0s6Qv6mQMYWEIXZDe7YeDr3N0vr3mVLJpTlCo8hYRxiCRkVYSDlIy)eI9j1FCqyF5488E8)A3(FTh4QG3geDZqBHMPGJUkTk2IuC4DWjesU2YkSMGiCa(gjmg2s7BfUPtb3mClibCRWTgg2gSD42G3j8UGDc3bSd42dd7kCfflJsfnttpG1a7(rHUDYm4qPsKmdg70lycDaIcZ4y5XN1HGEd7G6fcScLZrwvVK7jVA4otcVhkebVB(N3d)Z7I(SCEKx2RUJIbllCf1u(Wnmd(wK6VV9NXXxjY0eDTC8qPs7cLvyeoYxJPKGnQbxhC9Z56XSJzwWG1bS5MKm0lQ7TwiMWmLCzPOB0G9hg6k7IyCfNHMEjrsVLtoPyX7)WPNJcAdRR6P1e05AW1ZebR41qMdi)bw9CYokP4Q)t2gShbyVvsNivIEZKuk2HsaHddXRmuxUSyDNFBPoKdCTZRofYW1v4Y2C2Cwj0JDZ1X14Fy32Wm5rJHAi39vVdgKmm0xyyTiMLK7rGwfb2eW1CETSHZTLzV1Y64snTvjhf21TkipSAKCa3a0XckOdOQ1eMPNq3MLD(Q3s(fAnYrwhYrodQW5ABIGmh)QbWP9Mc9qN2Ufm4osbMjZrxjTM1edAMDHgUTSl(vmJjKNYL4wl4GY80vFeLZOJ8KidjBuCb6bv7zNLOJ3H9M7nyMfzihRcomx3iBJp4TZ5O3E45OrHAmLrZYjY7km6eGwzJZY4ByCilv2PxfsBx0o4j4hpUTRBvxXLCKfnbDL9ixFmC17(Adw3cOaNsHrqTP6SBWUvp2KEJ4QjJZ(JgyzzVzEJ8p8L5J4gCbS(5Q9BB5wCTBUUHVKT(I(Tw1wtm2HZmO91WBetEzr(gkCkSym82Z6)I0NK5ZRpXc(eVJv1bL)7hVKRNE(PGokZLWSmyJIdm4ajG15GlkQpL5DuPAMzH5cwbME2nN0rF6i3BjzvYNlsMmnSWR(MwG32eO74WoY2ZmCWf(tGX1D1ZHI)G1CD5MSBP)bgiH0iIdMjZGhI7fSqTxnL)BZbROJ2W7H(vE(PbpCMu9pqIZSqbdRjs6WgReZuzQHw9o3r0U9xD0pmpsH6ZiimRnd1en6fYvYZZYCqScbmzvzQzFT)gRqxxDPnxHQdLhAMNUnEq9ac8EwDYjs3OX7FAEwB(0kJMUYOMiTuG)lP0XRBH)2e9leiNgtVGM3jG78u(MNlwtOmQjQm0wKNicJBQuRkBnNRo5b(Cnd3DBpxZz9Dz9DCTBLgBJ9pB5LEwBk0l)K((02nJ9mMkroyQm1djpP252KUPgCTIKdJ0sudOBOJzQANKf9ep7Om0uMErEsuqrdtwioTLvXqKzCnV1dknbNIYTvZLUxPejgaIgcDupKKDHsdNz3rtmQJUjvVgtZEdvFfeBnUURmsGu14lVQogOWhFHOrIVj6PZo7Tc6n4cchplm6fWUB2w4Hy5Cy6MCK)rwWcS5jg9ZvA4hh97av2IFNOSN3b4XDMgBbrd0oWQKxKdIam4sgAuIOrO6FYszwXWtPSqXnjSLxaTTGX5UuWeVPmMGjd8JGPMDdW0HGpa22henuGhGBGaFi4ddFe4eWmNa(OHGtIbHpgCkS7pimRp(9qWhh(eHGhg(KWNkl8PHpd8iBgMle8OWN9mWNRQ2bEm4ZRbFb4lcFPncF5qW)N)G)kcWxne810GVUa8neGYTapUg8elrDHNud(MBf(wxiUj8TZcFNLiGW3vd(Eibdon89RXSGFarPGFirIGNQrguk4h5ZEGk(eNX2F3Xl5U)JoO(EHFSg80AWpPoYW24KbSJexqKQMz5OdNHqCo4wCtHE8NGWTQ0HXoRKoP2IKUKzD4CnwaIYLQMxQkaJt(lJU1HUiQva0iK90CWfHqewr0ka2RbWhIaDec3lOWfXXRm6WQgAdUT(M07Oec3Tepfbrm8HzUwA2UH(HduRO5U9)Ql)V6Kx0CEOhIgmWwsfhoswyWQLjVbopy5lt(2dZRsMqAeFhAnWHXkD9b3g3uhbUNtlB48ArcHl51azOkOXf3o7A3hC4yJn5ro(ErQ)Wuf0315vbTFWeR9T(kNrs2r1Oqz7cW9fuEmfIVwGH1fdVV1sb43BhW7xdlggUFyekM35AOWBTGDtWXWPu2M4r7Cy5UXeGO)(vH2M3BWokcIXPdf4RgiLQzRIO55iFOiyG4bJCJbobQfkuwvXWDeX6kxghXlHW6)70mO(480mOoc1mOAb1mOY5TindQcIxzIJPlnuVIzoq6HjGaX76zTOac1b7Poi9xZTgrqgvCbAlKhG6g0rkpc4iEIIq0L9naqNTf4NEEzeHF2s5)(fzrW9NhaUMvtX57fgOvUm0UIq7H31U9I3N44rp6axuq7ZErdTBlOgOM8X2F5fTy9zwwXkMs8Yi6kGOKdA8kSIJNoF(o75GB3JG0UHFvdykk28Hve)RbRZtG8fav9lbYhurJ9z7c6V8(huQ)7BWbYelfiCGZ2qXNr60ULZPoLiDw5Gm82IYUA4p3SiURCpTiw5JKu3HDUPfLEtLwu4nFArmgKoiT4WQSDLPF5029MyLsjsflwxkXGuwyArKJwxArkZ5sPfX4QFMXU04PfP8EyEX6vAxjilazxlxVH5pXSIuEYO((K(zeZeQMk7kxHDAma3kvIF2fI0U3xsUvHVdpnRjkOOM1EJvVZWY11kFWbIRXZt(u10RKMCjx3QoZ1CCROQ7E8sM8tgjQS5unQxPOfj9UnFPx71j9SxrP3f4enSdUqYtVitLRnr9xv5z5etAthcZeYtzFJxGXsdAeShk60PZkqAzuhtYzubJ65oSVHLBu(3jyhz56qrl1rC4Bj8rUE7TVC9k4m7gXtdNNA4EjfSV5LRVgScYktnsEdllhFNIhRMbXwrdIxmWJOnYLmlzrGoi1rw5NELjd3uR2YAEuHmNrHoYX6IBO7xDC9(e)ML8j4hc5U6PR(In2yz6FkBYU4sE7guH0TVvjfnMYO9a3KWmJl7OtB12EJ6MU0r7ROZm9KyU8JuZvACzJsmbhfnzZcmx0G41ZoJTJLnZXBkyssC47JTCcekn097xIXFa(J1L)5)plaAbjBAKX)mlhJhFmhHCMMJ(Vj4)rdTptkkulxGr90bJ9(N0inu0O6pbl8w4MW)VwkbVa8INRAb(ZWF5cObG)Qa8selgEzb4vQs8EvTQCTh(Kv5A3tD2JnK5Azl(iyx21Bv1fpJtqgONwRHDD)81v5bscJxjzrrRJnUs69kU3Gcq8zrWFJyqWRb)D41fG)bNBal6tkI(g4ygKWzGZJzqiDnQbUEAGAmxTmCbueKhfWqwze)sSULAioczRaIJ4vvehbFcWrqSoah5liG)szxQggoEtqpc4i5G4jnA1uRwKg8zQh7F1LZFr0)Cv6J7P0vTnDJ49trNHY91v0sMDLpz0KElH5)woMVhoMJmMAvAgDLbA(o8VOa67FLb6N9F3iqVyJvVSmODv)a4F2UDZ9Qj74WuJmKSlLNXL31)1LjgxiIbAkF(eJTV7P3ExgzkQnD8Lig)ULHyGuRQeJMGxtKQLXNB0gXn452AD8v)a)N)
```

### Bisector Report

_No response_

### PR DESCRIPTION
**Pull request by emptyrivers**
This is actually 2 problems in one:

- On initial spinup, our PRD anchor doesn't have a valid rect for 1 frame which would be fine, except we're creating it in the same frame we're anchoring dynamic groups to it. Thus, the dynamic group's children also won't have a valid rect. Fix this by forcing an early draw of the PRD anchor via an explicit GetSize call. (see https://warcraft.wiki.gg/wiki/API_ScriptRegion_IsRectValid for more details)
- After initial spinup, our PRD anchor is anchored to NamePlate1 (or something that's attached to it, depending on user's addons). Unfortunately for us, Blizzard in their extremely finite wisdom decided to make NamePlate1 a restricted region. Thus, calls to GetRect & friends on any frame in its anchor family will error. This went unnoticed because we explicitly suppress errors on this to avoid user shenanigans breaking WeakAuras. Fix this problem by checking if GetLeft errors: if so, temporarily reanchor the dynamic group to UIParent before computing a new rect for it.

Fixes #5023

### CODE REVIEW

File: WeakAuras/RegionTypes/DynamicGroup.lua [hunk 1]
```diff
@@ -1537,6 +1537,15 @@ local function modify(parent, region, data)
       Private.StartProfileSystem("dynamicgroup")
       Private.StartProfileAura(data.id)
       local numVisible, minX, maxX, maxY, minY = 0, nil, nil, nil, nil
+      local isRestricted = pcall(region.GetLeft, region) == false
```
Comment (InfusOnWoW) [inline WeakAuras/RegionTypes/DynamicGroup.lua:1540]: There's an api for that: IsAnchoringRestricted()

**Comment by InfusOnWoW** [comment]
I think that's on the reasonable side as far as hacks is concerned. It's doesn't look that complicated, so yeah I think we should add that.

**Review by InfusOnWoW — APPROVED** [review]
