### PR TITLE
Fix generating unique key for suboptions Close #3420

### LINKED ISSUE #3420: Adding more than one sub option corrupts the aura
### Description

Adding an option group and adding more than one sub option corrupts the aura (WeakAuras prints chat message, that aura is corrupted)

There may be some correlation between this issue and https://github.com/WeakAuras/WeakAuras2/issues/3419

### WeakAuras Version

WeakAuras 3.7.4

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

No error

### Reproduction Steps

1. Create Aura and add Option Group
2. Add Sub Option
3. Add another sub option
4. Aura is corrupted

### Last Good Version

WeakAuras 3.7.3

### Screenshots

_No response_

### Export String

_No response_

### PR DESCRIPTION
**Pull request by InfusOnWoW**

### CODE REVIEW

**Review by emptyrivers — APPROVED** [review]

File: WeakAurasOptions/AuthorOptions.lua [hunk 1]
```diff
@@ -533,10 +533,12 @@ local function ensureUniqueKey(candidate, suffix, options, index)
   local key = candidate
   local existingKeys = {}
   for index, option in ipairs(options) do
-    if option.key == key then
-      goodKey = false
+    if option.key then
+      if option.key == key then
+        goodKey = false
+      end
+      existingKeys[option.key] = true
```
Comment (emptyrivers) [inline WeakAurasOptions/AuthorOptions.lua:540]: what i wouldn't give for a good static type checker in lua...
