### PR TITLE
Dynamic Text: add props from child and multiselect auras.

### LINKED ISSUE #5272: Updating multiple aura display text causes lua error
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

i create 3 auras.
i use ctrl click to select the auras
i click into the text 1 field (currently showing %s).
i get a lua error

making this change on the group does not trigger a lua error

### WeakAuras Version

5.15.4

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Lua Error

```Text
1x WeakAuras/WeakAuras.lua:3791: attempt to index field 'trigger' (a nil value)
[string "@WeakAuras/WeakAuras.lua"]:3791: in function <WeakAuras/WeakAuras.lua:3790>
[string "@WeakAuras/WeakAuras.lua"]:3866: in function `GetAdditionalProperties'
[string "@WeakAurasOptions/WeakAurasOptions.lua"]:1751: in function `UpdateTextReplacements'
[string "@WeakAurasOptions/OptionsFrames/OptionsFrame.lua"]:925: in function `ToggleTextReplacements'
[string "@WeakAurasOptions/SubRegionOptions/SubText.lua"]:65: in function `?'
[string "@WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasInput.lua"]:18: in function <...tions/AceGUI-Widgets/AceGUIWidget-WeakAurasInput.lua:14>
[string "@WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasInput.lua"]:27: in function <...tions/AceGUI-Widgets/AceGUIWidget-WeakAurasInput.lua:27>
[string "=[C]"]: ?

Locals:
data = <table> {
 controlledChildren = <table> {
 }
 id = <table> {
 }
 anchorFrameType = "SCREEN"
 regionType = "group"
 config = <table> {
 }
 yOffset = 0
 xOffset = 0
 anchorPoint = "CENTER"
 authorOptions = <table> {
 }
 load = <table> {
 }
 triggers = <table> {
 }
}
triggernum = 1
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'trigger' (a nil value)"
triggerTypes = <table> {
 custom = <table> {
 }
 spell = <table> {
 }
 combatlog = <table> {
 }
 addons = <table> {
 }
 aura2 = <table> {
 }
 item = <table> {
 }
 event = <table> {
 }
 unit = <table> {
 }
}
```

### Reproduction Steps

see description

### Last Good Version

unknown

### Screenshots

image

### Export String

```Text
!WA:2!fx1wZXnsv4OicHODzJ9SEnXHaRXKesOOm2oBwi7duLL94nEZKzg0iBNSCzMws9mQxRrsPvlBpMRz2WI5omCjCFHHlfpavrn)e8VGtn1wufV6h2Fa5xaNwx8L41fvXl8Iu3h19rN(77781kRwiY6Mtp7nN(Lk0UGtbNDMvVfpyt9fRSw59Sc4ouUoXEDhEqy4i6EST3MWDM0miWtWchsIfUb8kHcwGFKgVtLMnJOcLbeFBmE1aMVWAHILnlA0VzSN3cmUThTHruiXMEgoXozFVSrKGWfA6mFMqZQj(kYvRRGZA1IYJU4v5zdFR(ouR4Mnn7es53UyPQlTsjDboXGeZjZ1nkK65TStK2ErXw0nO(IA4QzBnO(cZxZSEnZ5nm1JXFIvOhPdLV)YQYP4YmQvTyPsgjrSUnL4jCn8jTPrA9I9ZkbTb2bEXT9RjpbQwCIdlo6rpBpIpRnrEAEz4dUemMUFGpDxkjIwtWP(TeUNDOdwJYvuxwX8iQDGVtux5AKNh4Y6TjmFCVWLHRCw4QWNaUgo88pDedIhRLpCoocAYksPpEkmOTsyGET4mN1yoc3Nr3lG4SKEeBB64gTJr6sthbi7XHz0mS9irrYrwcIhECLdhALXZle4fWFnvv1QQZm9n7ktPScNYyrE6XK62lI61mHENZSsvJiBmlQ9TXmr5jRTKHvQ4XTF67IoTOHJw7bXeoDYLqTWKR5Ye0(8KkxUNDD6GOnZgLFXHz7Qgw9NXWJ1MjEMbPHsRofffv9OaUaUCpc3Uucg)OXZwZY(OkuDpeHrqYxSek0c4wgZV4YRuRBCeTKmHU7MU4un756IQ(uwTViWEdKHW66ck)J)5umhDbnsmOjhfdiFseevKfcDjQpjvOVK8lYZGvTfmkwSCVibnCE)wE0xCUyMZGnQERx)ZAEhBBIXtysmYN4TA6F4X4)vKOlu4BL1(0xknyP9udy(nd4PAlnl8dnzT0ky)k7CT(mCwTGyUn9sNAaX5nIX)QZDjBD6dMW8pnCwf4daNBOn2Y6eSPFTnzH0g7MpvYlUWZIYwn450GZRbJ8Cxfg9FbJzK0obFi4cHJIyw9wuFkNzxZnyZk(nGps4elKLJjRYdAXPrrtETAY9CD4f16LS7YiUCHZ8VhmuMG9J0agxB4rs3ErjVYtimbCr4ddxQNCBiGBVEdOa88WKAHJknn2GAM2oE3ah6F)uG5J3lmResbKp5Lo1PHpdCo0WiIiKnE4H8t9kJdJne7wKcDPkZ3zNlg(Xe0Te1tEKc01dRlyTP1d5uBMKIudN4yRjkBak)2)BtDLOWjpPS1oWPUSmASxYh3V)rF(vmRe(8jbr30ajtBN0bRppo9jPPITfnTT(HHx(K(dE0we7o1B6feWD3nzbsvaRzhehsezutmOE5kLlomB)(IeV0kRywA5YfHX4i6i)0WuD99YfKjl3o3xqT3(BpCKL4STN8ZhtCK9ftAAgwi9a6sqMmpbhj49ZdoX7XrjDGH8e5KwLBIDPRXjHDxlBq6zBdKBSWltchjf7o4gNWrxUC5Ig11RyAw5Ugl)Q32m8JEsOw6mLSSKwGhyXCaojDIMi86NuAY8UQlCrrOlQI7KbH5h23DylVGnxItFqm13Ut133mtp3ntbC5h2v(yXSBiu7kNjzMHwXcrGFf0ocVXQVmCQv3lmqoop59Kt232wDxST5vZJ4MSYCIqxoXnz91smTtkltxM96(y3JAYxkXWXJM830tnXTCPSwUIhctVe8PLxwaZM8CUKN3q(mCe8VoFMXtIpK7thI57cFoDPTfuwf(4PxvE0R7U()9la7MBD1iCS8HsH9ISickiCCFY6u09vExNWqINUghOC13oiOTcCFn4ozE7trM1yZKwl4UQqfOAybSQZDIqdgdzxlymyvRBSUt42lFRz3IZ8LxqGEkVFn4TBaRPb3tdwvzNRbV(LoLm4x40Wxm36f(snGVCUh75tSzZ9yH6s)vObANce01mXLZw6pcoan3geA2aSK2OObi0kXVd67MbGiWiXNdbGpvKZFSiSmVq4n25IW6QGhgR9uxjeqB9aieEaWHOhccxigR(nGnHTGo4Y3g(kkWxnbhHVg81HVHc8nvGhcDH3eEe8TAaVf8THDuGVtsVd8DNa(EDGVVY7c)GC5o8dHFUl8JHFc07fGFQc8Zst2psf(fkWVsf(LQWJDHF9OWVXf(TjQTBCm1wQ(735c)EunbVn8xBibFKf(tPjBvf4pRi5RnmV9kVwTzw9wZCiYEojflLF)Le(gfc)nx4p6kVSqsJ)HgGR8YJmMmlLNiBE0BmpgBMsAVN8z61zhInLfW)xjgKeogXGKfsmiLGedsphMyobBGdrmi8ISsoIk5feNpsN3nKSaYFzuIXGwBDF6wRBeFhovYlipI9sPDx)VAxuyJ35E)Np
```

### Bisector Report

_No response_

### PR DESCRIPTION
**Pull request by Boneshockx**
`GetAdditionalProperties()` should now collect all props from child auras if a group or multiple auras are selected.

conveniently also fixes #5272  :)

### CODE REVIEW

File: WeakAuras/WeakAuras.lua [hunk 1]
```diff
@@ -3862,12 +3864,30 @@ local wrappedGetOverlayInfo = wrapTriggerSystemFunction("GetOverlayInfo", "table
 
 Private.GetAdditionalProperties = function(data)
   local props = {}
-  for i = 1, #data.triggers do
-    local triggerSystem = GetTriggerSystem(data, i);
-    if (triggerSystem) then
-      local triggerProps = triggerSystem.GetAdditionalProperties(data, i)
-      if triggerProps then
-        props[i] = triggerProps
+  local dataCollection = {data}
```
Comment (InfusOnWoW) [inline WeakAuras/WeakAuras.lua:3867]: you should use TraverseLeafsOrAura, which does give you all leafs nodes (if its a group), or the aura itself if it isn't a group.

Comment (Boneshockx) [reply WeakAuras/WeakAuras.lua]: Thanks! I should have known that existed an hour ago.

**Review by InfusOnWoW — APPROVED** [review]
