### PR TITLE
yeet duplicate keys in custom options

### LINKED ISSUE #3368: Bricked custom options tab on a weakaura using only in-game options
### Description

I seem to have managed to break the custom options on a weakaura using the in-game options menu only: when editing this aura, clicking on the custom options tab does not navigate to a new tab; and going to another aura and navigating to custom options, then opening this bricked aura again presents me with a blank weakauras screen where I would expect the custom options screen.

While making a custom options screen, I had a large option group with multiple options. Finished with that, I pressed "add option" to work on a second option. Pressing the "add option" did nothing, and so I pressed it again, again to nothing. Now the custom options screen is entirely inaccessible in the weakauras menu.

Bugsack presents me with the error _"1x WeakAurasOptions\AuthorOptions.lua:2277: attempt to get length of local 'configList' (a boolean value)"_

All of this persists through ui reloads, game restarts, disabling of all non-weakauras addons - and even deleting and reinstalling the aura.

[Bricked aura here](https://wago.io/ZpOkshnrq)

[Full lua error here](https://pastebin.com/ECYEZUK6)

### WeakAuras Version

3.7.3

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

1x WeakAurasOptions\AuthorOptions.lua:2277: attempt to get length of local 'configList' (a boolean value)
[string "@WeakAurasOptions\AuthorOptions.lua"]:2277: in function <WeakAurasOptions\AuthorOptions.lua:2259>
[string "@WeakAurasOptions\AuthorOptions.lua"]:2398: in function <WeakAurasOptions\AuthorOptions.lua:2309>
[string "@WeakAurasOptions\AuthorOptions.lua"]:2494: in function `?'
[string "@WeakAurasOptions\OptionsFrames\OptionsFrame.lua"]:943: in function `EnsureOptions'
[string "@WeakAurasOptions\OptionsFrames\OptionsFrame.lua"]:920: in function `UpdateOptions'
[string "@WeakAurasOptions\OptionsFrames\OptionsFrame.lua"]:962: in function `FillOptions'
[string "@WeakAurasOptions\OptionsFrames\OptionsFrame.lua"]:1003: in function <...dOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua:1001>
[string "=[C]"]: ?
[string "@Bartender4\libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:72: in function <...aceBartender4\libs\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@Bartender4\libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:306: in function `Fire'
[string "@Bartender4\libs\AceGUI-3.0-41\widgets\AceGUIContainer-TabGroup.lua"]:156: in function `SelectTab'
[string "@Bartender4\libs\AceGUI-3.0-41\widgets\AceGUIContainer-TabGroup.lua"]:67: in function <...libs\AceGUI-3.0\widgets\AceGUIContainer-TabGroup.lua:64>

### Reproduction Steps

Unsure, through fiddling around with the custom options menus I have not succeeded in bricking any other auras in a similar manner.

### Last Good Version

_No response_

### Screenshots

_No response_

### Export String

_No response_

### PR DESCRIPTION
**Pull request by emptyrivers**
dunno how this happens but we can't keep corrupt data like that, unique keys are an invariant on custom options
fixes #3368

### CODE REVIEW

File: WeakAuras/WeakAuras.lua [hunk 1]
```diff
@@ -2288,65 +2287,69 @@ local function validateUserConfig(data, options, config)
       end
     end
   end
-  for i = #options, 1, -1 do
```
Comment (emptyrivers) [inline WeakAuras/WeakAuras.lua:2291]: turns out if this code ever did remove an option (except for possibly the last one), then the following block would immediately error since the `authorOptionKeys` table doesn't make any sense. So we just delay the removal of garbage entries in this array to the end of the function.

File: WeakAurasOptions/AuthorOptions.lua [hunk 2]
```diff
@@ -2528,7 +2558,7 @@ function OptionsPrivate.GetAuthorOptions(data)
           local i = #child.authorOptions + 1
           child.authorOptions[i] = {
             type = "toggle",
-            key = "option" .. i,
+            key = generateKey("option", child.authorOptions, i),
```
Comment (emptyrivers) [inline WeakAurasOptions/AuthorOptions.lua:2561]: small behavior change, the first option you create will have default key `option` instead of `option1`, then it'll go `option1`, option2`, etc. But I don't care about that change, nobody is ever expected to keep those keys in the first place

File: .gitignore [hunk 3]
```diff
@@ -11,3 +11,4 @@ format.bat
 .install
 .lua/*
 .vscode
+CHANGELOG.MD
```
Comment (Stanzilla) [inline .gitignore:14]: 👀 what did you test there? 😄

Comment (emptyrivers) [reply .gitignore:14]: i was playing around with the bigwigs packager and i did find a way to get it to install externals into a working copy, but not to keep it from generating changelogs
