### PR TITLE
classic: workaround GetSpellCount change in 1.13.03 #1849

### LINKED ISSUE #1849: spellcount not working since latest patch in classic dec 10th 2019
## Describe the bug

i'll use blind(rogue) as an example, i used spellcount in my text options to show many casts i am able to do(basically # of reagents on me) it was all working perfectly prior to the bg patch, and as soon as i got the update it stopped working.
**Do you have an error log of what happened?**

no only reporting other addons

### To Reproduce

1. import string
2. look at bottom right of square for the text(number)
3. make sure to have blinding powder in inventory
4. see no display of spellcount
5. open /wa and close to see 0 instead of nothing, but still incorrect

**Screenshots**

https://imgur.com/ZD5FFwL
**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

yes
**Which version of WeakAuras are you using?**

2.15.5 also in screenshot
**Are you on World of Warcraft Classic or Retail?**
- [ X] Classic
- [ ] Retail

**Was it working in a previous version? If yes, which was the last good one?**

it was always working fine, just until the BG patch in classic that went live on Dec 10th, 2019 that this started happening.
### Additional Info

```
https://wago.io/nWxm-__3b
```

### PR DESCRIPTION
**Pull request by mrbuds**
# Description
Work around GetSpellCount returning 0 for all spells since last classic update

copy/pasta from https://github.com/tullamods/Dominos/blob/master/Dominos/bars/getActionReagentUses.lua adapted to use localized spell name instead of spell ids

Fixes #1849

ps: it's highly possible a lib doing this will be release

### CODE REVIEW

**Comment by Vardex** [comment]
What about this lib? https://github.com/Ennea/LibClassicSpellActionCount-1.0

**Comment by mrbuds** [comment]
slot doesn't work, function need to take spell name

**Comment by mrbuds** [comment]
but yeah that could be added to this lib

**Comment by InfusOnWoW** [comment]
That's ugly....

File: WeakAuras/Types.lua [hunk 1]
```diff
@@ -2223,4 +2223,168 @@ if WeakAuras.IsClassic() then
   end
 
   WeakAuras.glow_types.ACShine = nil
+
+  -- from https://github.com/tullamods/Dominos/blob/master/Dominos/bars/getActionReagentUses.lua
+  WeakAuras.spell_reagents = {
+    -- Druid
+    -- Gift of the Wild
+    [GetSpellInfo(21849)] = 17021,
```
Comment (emptyrivers) [inline WeakAuras/Types.lua]: spell data is asynchronously loaded, I thought. So I would expect that in some cases this'd cause a `table index is nil` error, and break things.

**Comment by mrbuds** [comment]
LibClassicSpellActionCount-1.0 author may add functions suitable for this use case
https://github.com/Ennea/LibClassicSpellActionCount-1.0/issues/1#issuecomment-566003178

**Comment by InfusOnWoW** [comment]
Okay, someone else having to deal with the uglyness is better :)

Though I the more I see the wow classic devs work, the less sure am I that they know what they are doing.

**Comment by mrbuds** [comment]
They change their API like if they didn't know that addons devs will reproduce same behavior in a less effective way.

**Comment by Stanzilla** [comment]
@mrbuds sup with this?

**Comment by mrbuds** [comment]
Lib was updated to add the missing function needed, i'll work on it

**Comment by mrbuds** [comment]
Redid this using the lib, package tested on classic, and it's working fine
