### PR TITLE
Fix recent changes to ticks.

### LINKED ISSUE #2247: Tick Mode select dropdown doesn't have value by default
## Describe the bug

When I create a new tick the Tick Mode select dropdown doesn't have a value.

**Do you have an error log of what happened?**

No error.

### To Reproduce

1. Create a new progress bar
2. Add a Tick subregion
3. See that it's missing a value in the Tick Mode select dropdown

**Screenshots**

**Which version of WeakAuras are you using?**

2.17.9

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [X] Retail

**Was it working in a previous version? If yes, which was the last good one?**

It's the first time I use tick subregion.

### PR DESCRIPTION
**Pull request by nullKomplex**
# Description

Fixes #2247

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested

- [x] Recreated STR in ticket
- [x] Recreated STR in discord report

### CODE REVIEW

File: WeakAurasOptions/SubRegionOptions/Tick.lua [hunk 1]
```diff
@@ -48,7 +48,6 @@ local function createOptions(parentData, data, index, subIndex)
       name = L["Tick Mode"],
       order = 3,
       values = WeakAuras.tick_placement_modes,
-      desc = L["Relative mode positions the tick at the position relative to the total width of the progress bar.\nAbsolute mode positions the tick at a fixed value."],
```
Comment (Stanzilla) [inline WeakAurasOptions/SubRegionOptions/Tick.lua:51]: removed by accident?

Comment (Stanzilla) [reply WeakAurasOptions/SubRegionOptions/Tick.lua:51]: nvm saw the discord message
