### PR TITLE
Smallfix

### LINKED ISSUE #2098: Trigger "Pet Behaviour = Defensive" doesn't work
## Describe the bug

Expected text to show up on screen when pet stance was set to defensive, nothing happened.

**Do you have an error log of what happened?**

No LUA errors. Not going to download other addons to test if this one has an error report on them.

### To Reproduce

1. Create new text aura
2. Set display text to any letter/word
3. Set trigger to Status > Pet > Pet Behaviour > Defensive
4. Set pet stance to Defensive
5. See error (nothing happens)

**Which version of WeakAuras are you using?**

2.16.6

**Are you on World of Warcraft Classic or Retail?**

Retail

**Was it working in a previous version? If yes, which was the last good one?**

It was working before the latest WoW patch. Downloaded about a dozen old "Release" builds to try and find a build it worked on just now, none of them worked.

### Additional Info

Playing a Warlock, tried with several different pets. Changing trigger to Pet Behaviour = Assist then changing pet stance to Assist makes text appear on screen as expected. Same with Passive. Bug is only with Defensive stance exclusively. Testing as an Icon aura instead of Text aura also doesn't fix it. Problem is with Trigger.

### PR DESCRIPTION
**Pull request by mrbuds**
# Description
Fixes #2098 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

File: WeakAuras/Prototypes.lua [hunk 1]
```diff
@@ -6531,30 +6531,29 @@ WeakAuras.event_prototypes = {
...
-            repeat
-              name,i, _,active = GetPetActionInfo(index);
-              if (active) then
-                activeIcon = _G[i];
-              end
-              index = index + 1
-              if WeakAuras.IsClassic() then
-                if name == "PET_MODE_AGGRESSIVE" and active == true then
+            local name, i, active, behavior, _
+            for index = 1, 12 do
```
Comment (Vardex) [inline WeakAuras/Prototypes.lua:6535]: Use `NUM_PET_ACTION_SLOTS` instead of 12
