### PR TITLE
Bossmod Timer fix

### LINKED ISSUE #4583: Bigwigs timer triggers don't fire if offset timer >= remaining time
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

If I make a bigwigs timer trigger with remaining time <= 5 and offset timer = 5 I expect the trigger to fire when the bigwigs timer reaches 0 and stay active for 5 seconds. Instead it never fires.

Likewise with remaining time <= 1 and offset timer = 5 I expect the trigger to fire 4 seconds after the bigwigs timer reaches 0 and stay active for 1 second. Instead it never fires.

However, with remaining time <= 5 and offset timer = 4.9 the trigger fires when expected with 0.1 seconds left on the bigwigs timer and stays active for 5 seconds.

### WeakAuras Version

WeakAuras 5.7.0

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Lua Error

```Text
No errors are generated.
```

### Reproduction Steps

1. Create a text weakaura that displays some text
2. Add a BigWigs timer trigger with Message Contains test, Remaining Time <= 5, Offset Timer = 5
3. Close weakauras
5. Type the following in chat: /localbar 10 test

The trigger should fire when the test bigwigs timer reaches 0 and stay active for 5 seconds. However, the trigger doesn't fire. But if you change the offset timer to 4.9 it works as expected.

### Last Good Version

_No response_

### Screenshots

_No response_

### Export String

```Text
!WA:2!1rvZUTTrqyROdbLiWjLhmkIlqeCrSBrbmkkGt8HMdIkKiUqXsLIok9e1sUdPwxQDxS7szlFuOf1N9JGo3t6rOpbec9jWpc(jiZkQAeuuZdKZS73833mdBe4oXL6sV(aLO0uW4GQ3zrDp5uF1L9YY0GPH87PmTSGmlcU0eNjutiMyzSHnbIPZ4KjS0yZyfOhlkOnxPhtOIl(1AJ)6Tws4PJfQ(cg3K0X)0i)qzRh2H1AnKplTuBetSiotsjgieMcCZTKs8uIHLoKrnJ9AJQksQHj46xfQneLXjjJXz6XoE4hJZCJILNdk927R2iETRslHIItOps6QGjeeippwibfbD3E)0BcXQc0o3C)LUhTYyt2)fZcmg0V9GxQp47wqHKYSSOz4vVZVB)GZ66zqLecLIz1T6YK1P(aee7YLXDApikEqu7WipRlXxAZ8sneB1g5vIjDILCa1s7PBY0XZ3iODU3J9va6XWb9972nbng4u3JQCw5XYhYY1TIqcvTY6K7RJrlSQ1yhDtjFdJ4i)sljofIQ1FVGc)1wY9E4(0ebngzcyKC)hgubKtsNfNvieQr3OHIS6XaVErr9EVxMGBKplqXUQ1VusOO7iTIIwGLxiKB7OpFNQDxHQjK0FlhNp5uVcbHgKyify9Vt4KYcdZXdPM0DQo2jmTGO1wjpn7kWkm3gKbOYSndMFSEWS5c16yyBBvVijvWZy5o3q4m70LG)QQTd(BGOHbgfWZnJFC1UECbhwrlvRreBBYknGMs1ZTqx7lpplvhu1gnOYRQt1BR8XVp9)EI8BEyEtQGuMgJrt5U)VOQfcTGPlSjaB9gasaIcH6NBIpQZXfiw2mVU(brlmI0PyYIG(Qg)5xShJkDXPKlUFkPvKDk8cHIourKZhUryzMcxeqkaBnnVREtoWEKTutg0j03)u1Sn)N4hlz0LzhFY50ob039b(kCxfX3twNBl)SkrzdxRxkxw3t6SoRB0OrtCV6sGUE3(3FYsgVUqr7DUdhCafNu8H664pC1HhD4Rp8hCN(pF8td
```

### PR DESCRIPTION
**Pull request by mrbuds**
fix #4583

### CODE REVIEW

File: WeakAuras/BossMods.lua [hunk 1]
```diff
@@ -129,10 +128,19 @@ Private.ExecEnv.BossMods.DBM = {
         if bar.expirationTime < now then
           if bar.scheduledScanExpireAt == nil or bar.scheduledScanExpireAt <= GetTime() then
             self.bars[timerId] = nil
+          else
+            if self.nextExpire == nil then
+              self.nextExpire = bar.scheduledScanExpireAt
+            elseif bar.scheduledScanExpireAt < self.nextExpire then
```
Comment (mrbuds) [inline WeakAuras/BossMods.lua:134]: can't `bar.scheduledScanExpireAt` be nil here?

Comment (InfusOnWoW) [reply WeakAuras/BossMods.lua:134]: No if it is nil (or <= GetTime()) we would be in line 130

Comment (mrbuds) [reply WeakAuras/BossMods.lua:134]: indeed sorry

your changes are good, i did only tests with auto-clone and didn't think enough about nextExpire
