### PR TITLE
dynamic group custom sort: improve error message when custom grow fun…

### LINKED ISSUE #1598: Error when you don't nil check activeRegions[i] in the CustomGrow function
**Describe the bug**

**Do you have an error log of what happened?**
 

**To Reproduce**
1. Create a Dynamic Group
2. Create any Aura inside that Dynamic Group
3. Try to use this CustomGrow function
`function(newPositions, activeRegions)
    local mid = #activeRegions / 2
    for i = 1, 4 do
        newPositions[i] = {
            40 * (i - mid),
            0.5 * (i - mid)^2
        }
    end
end`
4. Can't close the Lua editor by saving the code. You have to use the "Cancel" button. You can save your code by using Ctrl+S but that also won't close the Lua editor.
5. The "/wa" in the EditBox doesn't disappear and somtimes you have to press enter several times until the WA Options Frame shows up.

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes

**Which version of WeakAuras are you using?**

2.14.1

**Was it working in a previous version? If yes, which was the last good one?**

Yes in 2.13.4

**Additional context**
I know that you can avoid this error by nil checking activeRegions[i] and at first i wasn't sure if i should report this as a bug but i thought that it can cause some errors when people don't update their auras that are not "well written". I also apologize for my very bad english :( .

```!vBvBZjUnq4FmD6m315oW4aD61z6hietdz4acYCPVmvXcBzhD1wYJKCasNZ)27kj7ab4UE9BTdzaR1R2D1Z(Spk4E4qmQaJsWifg53Px)o9mRaR7MNMQOA8mpm6rQuXeC8m4LsAg8y4Usk44ooPGfNjfvLyeHZkiAJFMGsy2F1wh5cUX9kP9937mQOXcEIcRHh1eP(R39ugNPE4R2Fyh5ScgCwgGrvm4WMC7nF8MHPxx8lZalYCm6bTUu9JD7UHKj6WeDfR(1R6p4dVlSlCMjY4PuEM(b8Sl(EapIRuArXplfBGAPIhBY6R40nlekM5z1BQJiG1hPlTOL6113uh5(KlIj51rfSK6OFQo6BEHF1rDRJ837CQqwhXSo2dIz)6OeX(32(5Wm)7S)W6(FDQBTF67vh9D1rVcI7BTfYRFZN3zVodo276p5FQ)FAVjkpP(g4lazv0PwGFngT9a(0AHmHkdsYG2uV6OfST08w(d14SQADdIanzO9jjjSkfEMVNb9f8uwM7fkAbqoHO0XRd8kfGTuhnvODCrt(mT8qQshiLcPnaaHJRhdyVz9YHxnzfQTSqSNGq4Jrz2(7OvOW5VhIbxtLCs(hANf89B3HPIjwsGPCbpz6MQRHwFiL1shD7Bc3cigcgp(bHCHascKXGzHblbJvAW48s9ECWTVwKSVPgzj3XsmmZbUvUjZLxbzxajVz2aQKSmOsTOpj(ptKIYrIC40hAkaZF(2VVW(DFWXodmzmwKxvWrLKyhUAMPyNurhgkpBO8SHYZgQE7D8YMCJrxMZE6jIeMccfICndmPfXpR08dE2En0c2N7CbXknfNtuwKUOc2ylMQkPXNA00mp2iqlV3fJ1MLKCwgFpSRLmduPChhyVv8gtUt8(fMuMNpjPbkCYoeqfY3SjGeGkZj7m0t6JutN9AkjhAvg6T1YcjnLTfJqlcMoDVzuvQ189JgIcVhfoCjKlqPL2KOe6AWdxJ(6GPlgVAQ9GzNhYtpMgz5wJLW(DBbnAzqaO7LAmbhhIMyHxLdO9nX5rWsFFt)(zy4Wleev6CMHxnFv40jZcE5veXFrILLn8zlQ)zXyN4BiDREvzIrVav187HxnPH3)F7RKsfqN2Q10Z)fnUlNhAvCoROWhHtplDhgnnyCyZTz3USC07(nVvSnemAdmNDNKaJt398tNv76mYlhZisykddo0ILF75NqpuxhcPWG3Xojj0qyTt9DgDtD0fNkFCS(9r6(gmcJglzpvhDBfjXuzGGr4)NNsrUB8dDf47fjad4T98S)xkFzbUZPLDovplDClT9IbBB6F39thCfRDTzqCcCLYZdIGr8Fp```

### PR DESCRIPTION
**Pull request by mrbuds**
Improve error message when custom grow function return bad data

Fixes #1598

### CODE REVIEW

File: WeakAuras/RegionTypes/DynamicGroup.lua [hunk 1]
```diff
@@ -1049,7 +1049,12 @@ local function modify(parent, region, data)
       local max = #newPositions
       for index = 1, max do
         if newPositions[index] then
-          newPositions[self.sortedChildren[index]] = newPositions[index]
+          local data = self.sortedChildren[index]
+          if data then
+            newPositions[data] = newPositions[index]
+          else
+            error(("'%s' Grow function return position for an invalid region"):format(region.id))
```
Comment (InfusOnWoW) [inline WeakAuras/RegionTypes/DynamicGroup.lua]: This stops the rest of the code, I'd just do something like geterrorhandler()(L["Error in ..."]), but otherwise continue
